### ISSUE TITLE
[Bug] Wrong error message

### ISSUE THREAD

**Issue by ArchangeGabriel** [OpenSMTPD/OpenSMTPD#687] opened 2016-04-29 15:06 UTC
Some of my users (including me) receive error messages like this one:

>    Hi!
>
>    This is the MAILER-DAEMON, please DO NOT REPLY to this e-mail.
>
>    Your message was successfully delivered to these recipients.
>
>********@etu.univ-lyon1.fr: Network error on destination MXs
>
>    Below is a copy of the original message:

(I’ve cut it here)

But the message was NOT successfully delivered, so that is confusing. I’ve pasted the whole log here (address are obfuscated, and I’ve removed every other mail sent during that time):
https://gist.github.com/ArchangeGabriel/a6f16bc0bf5567bdcdb1f8750c155e1a

Obviously, the error is destination not supporting TLS (which I consider as a major flaw, and let my users know about it), but I was wondering whether that much connection tries was a normal thing.

**Comment by snimmagadda** [comment] 2016-04-29 16:37
Please specify which version of OpenSMTPD you are running.

**Comment by ArchangeGabriel** [comment] 2016-04-29 17:03
Sure, 5.7.3p2.

**Comment by ArchangeGabriel** [comment] 2016-05-03 11:21
And, 4 days later:
```
    Hi!

    This is the MAILER-DAEMON, please DO NOT REPLY to this e-mail.

    Your message was successfully delivered to these recipients.

amandine.escalier@etu.univ-lyon1.fr: Envelope expired

    Below is a copy of the original message:
```

Again, a normal behaviour, but a wrong message. I had an idea thought. Could this be because of the use of DKIMproxy? Like, OpenSMTPD successfully delivered to DKIMproxy, but failed to deliver to the real destination, so that it sends a DSN but with delivery to DKIMproxy as the success value?

**Comment by poolpOrg** [comment] 2016-05-03 14:20
@snimmagadda ?

care to have a look at this please ?

**Comment by snimmagadda** [comment] 2016-05-08 16:20
@ArchangeGabriel A similar issue was fixed on Feb 3rd 2016 which @poolpOrg correctly pointed out that it was not part of 5.7.3p2. Could you please try master branch and report if you issue still persists.

**Comment by poolpOrg** [comment] 2016-05-17 07:37
@ArchangeGabriel any feedback ?

**Comment by poolpOrg** [comment] 2016-05-22 16:55
OP timeout, we can't reproduce and issue is likely fixed with the fix from 2016/02/03 which was not part of the 5.7.3p2 release.

Closing ticket, it can be reopened if issue is reproduced with latest release.

**Closed by poolpOrg** 2016-05-22 16:55 UTC
Labels: wait feedback

**Comment by ArchangeGabriel** [comment] 2016-05-22 17:39
Yes, sorry, I’m quite busy at the moment, can’t test that. Will see if it indeed get fixed with next update.

**Comment by ArchangeGabriel** [comment] 2016-06-15 17:49
So, tested 4 hours ago, just received a “Delivery status notification: delayed”. :)

I expect the error message in 7 days to be correct too. ;)
