### ISSUE TITLE
LMTP broken: "illegal seek"

### ISSUE THREAD

**Issue by crepererum** [OpenSMTPD/OpenSMTPD#694] opened 2016-05-21 10:49 UTC
## Env
- Worked in: `5.7.3p1`
- Broken since: `5.9.2p1`
- System: Debian 8.4

## Description
LMTP delivery to local unix socket is broken. [This `fflush` call](https://github.com/OpenSMTPD/OpenSMTPD/blame/8b849a926e4bc7c6a6c6877b5930f7acc67c2aeb/smtpd/delivery_lmtp.c#L187) ends up with `Illegal seek`, same holds for the `getline` call afterwards (in case you comment out the `fflush`). It seems that LMTP stream under the former version were handled differently.

**Comment by poolpOrg** [comment] 2016-05-22 16:18
What LMTP server are you using ?

**Comment by parchd-1** [comment] 2016-05-22 16:49
I can confirm that this is an issue with dovecot - I've spent most of the day trying to debug it, but I haven't made any real progress.

Things work as expected when manually communicating with opensmtpd using socat. When communicating with dovecot, opensmtpd disconnects before giving "MAIL FROM:...".

There was a bug in glibc 2.23 regarding fflush which I considered as possibly relevant, but led me nowhere. I've also considered differences between BSD/Linux socket implementations but I didn't find anything clearly relevant.

It would be interesting to hear other ideas - I'm stumped.

**Comment by crepererum** [comment] 2016-05-22 19:03
Yes, in my case it's dovecot as well. Currently it's version `2.2.13`. It is somewhat weird that socat seems to work then (but didn't test this myself).

**Comment by parchd-1** [comment] 2016-05-22 21:29
I'm using dovecot 2.2.24. I had a look at the debian package list and realised from version numbers that my messing about with glibc was a complete waste of time. I should have done my homework before diving in head first.

**Comment by parchd-1** [comment] 2016-05-25 07:49
The problem here is far simpler than I thought. I made a stupid mistake when I used socat and so completely missed the obvious.

The problem is that after the LHLO, dovecot sends *multiple* lines:
```
250-Hostname\r
250-STARTTLS\r
250-8BITMIME\r
250-ENHANCEDSTATUSCODES\r
250 PIPELINING\r
```
whereas smtpd only anticipates one, which it receives with getline(...).
This means smtpd tries to write back to the socket while there is still data to be read.
I'll test my solution and submit a patch.

**Comment by ArchangeGabriel** [comment] 2016-06-01 12:19
I can confirm this too. :( That’s a quite huge issue, mails not being delivered to users anymore… I should have tested it a bit more.

Is there a way for me to be sure waiting mails won’t be discarded until a proper fix lands? Is downgrading OpenSMTPD safe (for messages to be delivered)?

Also, is there a way to configure OpenSMTPD to send mails to a specific address when they are TempFail issues in the queue?

**Comment by ArchangeGabriel** [comment] 2016-06-02 11:13
That’s starting to be urging, some emails are getting close to the 4 days limit (only some hours remaining).

**Comment by systemfreund** [comment] 2016-06-02 11:26
@ArchangeGabriel i have the same problem and downgrading worked me at least.

**Comment by ArchangeGabriel** [comment] 2016-06-02 11:27
@systemfreund Are you on ArchLinux too (to ensure we have most things in common)? Messages in queue were correctly delivered after downgrade?

**Comment by systemfreund** [comment] 2016-06-02 11:36
@ArchangeGabriel yes i am on Arch and messages were delivered correctly. But I must add, that i am using this for my private email only. I am only managing like three accounts or so. I don't know on what scale you are operating and whether something still could go wrong.

**Comment by parchd-1** [comment] 2016-06-02 11:39
@systemfreund @ArchangeGabriel 
As you can see, I have already submitted a pull request that deals with this ( #699 ).
Rebuilding the package with the patch applied will fix your issue until the next release.

**Comment by ArchangeGabriel** [comment] 2016-06-02 14:13
Thanks @parchd-1, it worked.

**Comment by poolpOrg** [comment] 2016-06-05 12:12
This has been fixed in git and synced to github, upcoming snapshot + release will have this.

**Closed by poolpOrg** 2016-06-05 12:12 UTC
