### ISSUE TITLE
smtpd crashes on trying to equeue outgoing messages for relay

### ISSUE THREAD

**Issue by kyrias** [OpenSMTPD/OpenSMTPD#995] opened 2019-11-12 18:40 UTC
Running OpenSMTPD 6.6.1p1-2 and the config linked below, anytime a message is returned from `dkimproxy.out` on port `10028` and is to be relayed, smtpd crashes with the below backtrace.

Log and config available [here](https://gist.github.com/kyrias/0884179946a954926bbb2241b429b9a5).

```
#0  0x00007f0c3b209bfe in __strcmp_avx2 () from /usr/lib/libc.so.6
#1  0x000055fbe0ca1399 in dictentry_cmp (a=0x7ffe440d98e0, b=<optimized out>) at ../../smtpd/dict.c:266
#2  _dict_SPLAY (head=head@entry=0x55fbe16710d0, elm=elm@entry=0x7ffe440d98e0) at ../../smtpd/dict.c:269
#3  0x000055fbe0ca17ec in _dict_SPLAY_FIND (elm=0x7ffe440d98e0, head=0x55fbe16710d0) at ../../smtpd/dict.c:40
#4  dict_get (d=0x55fbe16710d0, k=<optimized out>) at ../../smtpd/dict.c:107
#5  0x000055fbe0cd7b6d in table_find (conf=<optimized out>, name=<optimized out>) at ../../smtpd/table.c:110
#6  0x000055fbe0cc9013 in ruleset_match_from (evp=0x7ffe440daaa0, r=0x55fbe1697d20) at ../../smtpd/ruleset.c:96
#7  ruleset_match (evp=evp@entry=0x7ffe440daaa0) at ../../smtpd/ruleset.c:237
#8  0x000055fbe0cad521 in lka_expand (lks=lks@entry=0x55fbe1698480, rule=<optimized out>, xn=0x55fbe169a190) at ../../smtpd/lka_session.c:319
#9  0x000055fbe0cad853 in lka_resume (lks=0x55fbe1698480) at ../../smtpd/lka_session.c:204
#10 0x000055fbe0cadbbd in lka_session (id=12039383155050611034, envelope=envelope@entry=0x7ffe440ddfd0) at ../../smtpd/lka_session.c:102
#11 0x000055fbe0ca8f59 in lka_imsg (p=<optimized out>, imsg=<optimized out>) at ../../smtpd/lka.c:150
#12 0x000055fbe0cd433e in imsg_dispatch (p=0x55fbe172afb0, imsg=0x7ffe440e0940) at ../../smtpd/smtpd.c:1851
#13 0x000055fbe0cb1976 in mproc_dispatch (fd=<optimized out>, event=<optimized out>, arg=0x55fbe172afb0) at ../../smtpd/mproc.c:208
#14 0x00007f0c3b5092ce in ?? () from /usr/lib/libevent-2.1.so.7
#15 0x00007f0c3b509b7f in event_base_loop () from /usr/lib/libevent-2.1.so.7
#16 0x000055fbe0ca9c4f in lka () at ../../smtpd/lka.c:721
#17 0x000055fbe0c99ba0 in main (argc=<optimized out>, argv=<optimized out>) at ../../smtpd/smtpd.c:821
```

**Comment by poolpOrg** [comment] 2019-11-12 19:46
This is caused by a logic error in the handling of `from socket` rules.

Depending on the order of your rules and if you're using network connections or socket enqueuing, your ruleset may or may never hit the bug.

I have crafted a fix which I'll commit in a few minutes and which will be part of our next minor release in December (6.6.2p1).

In the meantime, you can either apply the following diff on top of 6.6.1p1, rearrange your rules to not have `from socket` or rearrange your rules so that `from socket` cannot be reached from a network listener either by adding a tag to your network connections and adding a `! tag` on your `from socket` rule, or by putting your `from socket ` rule last and ensuring that all network connections are caught by previous rules.

[from-socket.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/3837913/from-socket.txt)

**Comment by poolpOrg** [comment] 2019-11-12 20:34
Committed here:

https://github.com/OpenSMTPD/OpenSMTPD/commit/64a905d9cb8b3dba05a56c200fd027096360a20d

You can apply the ruleset.c and to.c diffs

**Closed by poolpOrg** 2019-11-12 20:34 UTC
