### ISSUE TITLE
Support for ECDSA (elliptic) CA server certificates

### ISSUE THREAD

**Issue by sysfu** [OpenSMTPD/OpenSMTPD#556] opened 2015-04-25 21:15 UTC
This was [raised on the mailing list](http://www.mail-archive.com/misc%40opensmtpd.org/msg01773.html), creating an issue here to track the progress.

> > I'm in the process of switching out existing RSA Certificate Authority
> > server certificates for ECDSA (Elliptical Curve DSA) ones.
> > 
> > Are ECDSA certs supported by OpenSMTPD? Or does that depend completely on
> > the chosen SSL library, i.e. OpenSSL, LibreSSL, BoringSSL, etc?
> 
> Gilles reply:
> They are not supported yet but they should be soon.
> Basically, we rely on privilege separation for handling private keys and
> it requires writing slightly more code than the usual. There's been some
> discussion going on about this on another OpenBSD project and we'll pick
> the change when it's available there.

**Comment by poolpOrg** [comment] 2015-04-29 03:52
FTR, still no ECDSA privsep in relayd/httpd on OpenBSD, waiting for it.

**Comment by nikolavouk** [comment] 2017-06-15 20:15
Is there any update on when ECDSA support for opensmtpd is expected? 

Right now it's failing with:

pony express: ssl_ctx_create: could not fake private key: No such file or directory

and it seems that the underlying of libressl depends on it being RSA.

https://github.com/OpenSMTPD/OpenSMTPD/blob/73d3fd78ceba78a357d5e30b3c11fde590857e39/smtpd/ssl.c#L426
>> SSL_CTX_use_PrivateKey() adds pkey as private key to ctx. SSL_CTX_use_RSAPrivateKey() adds the private key rsa of type RSA to ctx. SSL_use_PrivateKey() adds pkey as private key to ssl; SSL_use_RSAPrivateKey() adds rsa as private key of type RSA to ssl. 


I guess the answer is to replace that with a different api that reads ecdsa public keys and uses it for the private key instead?

**Comment by poolpOrg** [comment] 2017-07-31 17:29
No update, no.

The problem is that it's not just about replace the functions in ssl.c

We need to rewrite an ECDSA engine similar to the one reyk@ wrote for RSA and this is not only tricky but requires time which is currently spent on another big project with OpenSMTPD.

We still want to do it but it's not going to happen soon unless someone volunteers to help writing the engine.

**Comment by MrSorcus** [comment] 2018-05-18 08:36
Up. Any news on this?

**Comment by n8v8R** [comment] 2018-07-25 20:41
> We still want to do it but it's not going to happen soon 

That was about 1 year ago, notwithstanding the initial report 3 years. Is there any development?

I got bit shocked after having switched to OSMTPD and issued EC certificates to see

> pony express: ssl_ctx_create: could not fake private key

which suppose is caused by the lack of support for EC?

**Comment by poolpOrg** [comment] 2019-06-02 09:58
I wrote the ECDSA privsep engine, it will be part of next release.

**Comment by poolpOrg** [comment] 2019-06-05 06:41
code committed in -current, this will be synched to github shortly

closing this long standing ticket

**Closed by poolpOrg** 2019-06-05 06:41 UTC
Labels: feature request
