### ISSUE TITLE
"-" delimiter for tags

### ISSUE THREAD

**Issue by nordin** [OpenSMTPD/OpenSMTPD#476] opened 2014-09-08 17:28 UTC
Systems that use legacy address tags with a hyphen i.e. "user-tag@", where the tag is user generated and arbitrary, are currently impossible to upgrade to opensmtpd. It would be great if both the standard tag delimiters ("+" and "-") where supported.

**Comment by kevlar700** [comment] 2015-03-20 12:43
A filter would work fine and give flexibility but I would like to throw in a couple of points for consideration for what patches may be acceptable after the more straight forward filter option has been implemented?

The delimiter is actually a very useful antispam measure and perhaps being able to arbitrarily change the delimiter such as postfix allows would be a step further than the spammers could decide to cope with, IF spammers ever start interpreting the use of '+'.

I believe a filter would mean that the + would always match.

The downside as Gilles has understandably mentioned as significant is that it would affect the configuration such as virtual expansion, though for imap compatibility (no domain understanding, just usernames) I have found a little scripting to create a vusers file that smtpd actually uses is the best option to keep the smtpd config that I like so much anyway and so an extra line in vusers with a delimiter wouldn't matter so much. Of course on the other hand, I probably wouldn't have been inspired or able to make it so neat for the admin starting with other MTA configs.

http://mlmmj.org/archive/mlmmj/2007-12/0000014.html

It seems other MTA keep track of the accepted part upto the delimiter and even pass it to other programs but there obviously isn't a standard because they apparently all use different env variables to do so.

mlmmj seems to work fine with a - delimiter including subscription confirmations and their mailing list doesn't suggest asn understanding of issues when asked but the README files do mention "probably won't work" as - is used for some internal delimiting.

**Comment by jdelic** [comment] 2016-03-06 17:02
I just wanted to add my vote to this feature. I'm currently looking into upgrading a qmail site to opensmtpd. Since qmail uses "-" as it's mailext delimiter that seems to be impossible.

I don't understand why opensmtpd when faced with a `smtpd.conf` rule to deliver to system users couldn't check whether "user-ext" exists and delivering there, before stripping "-ext" and and trying to deliver to "user", which is *exactly* what `qmail-getpw` does?

As it is right now, I have to figure out a way to rewrite "-" to "+" in all incoming email... does there exist a standard way to do that by now? Any pointers would be appreciated.

**Comment by poolpOrg** [comment] 2016-08-31 10:21
After long and heated discussions, I caved in and introduced a new keyword to allow overriding the + subaddressing delimiter.

The code has been committed to CVS and will hit github soon, it will be part of upcoming snapshots.

Note that it will not be part of upcoming OpenSMTPD 6.0.0 but will very likely be merged into next minor version.

**Closed by poolpOrg** 2016-08-31 10:21 UTC
Labels: feature request

**Comment by jdelic** [comment] 2016-08-31 13:03
@poolpOrg That's great news! :)

In the meantime, I have a filter in development (since the filter API is still very much in flux) that is supposed to accomplish the same thing here: [opensmtpd-plusdashfilter](https://github.com/jdelic/opensmtpd-plusdashfilter). I need this to move my decade old qmail installation. It might help other people while waiting for native opensmtpd support at some point.

**Comment by 0xErnie** [comment] 2016-12-05 11:59
I am a bit puzzled since the issue is closed, but I can't find any hints that the code has been published to github for about three months now.

**Comment by poolpOrg** [comment] 2016-12-05 13:08
It was introduced with commit 5d84737b42c5fdc38a572e69a6875a05b3e6d1de

You'll find the documentation in smtpd.conf(5):

     subaddressing-delimiter delimiter
             Redefine the subaddressing delimiter from the default `+' to
             delimiter.

             Any printable character valid in an email address is allowed,
             except spaces and `@'.

             The first character in the user-part of an email address that
             matches delimiter is considered to be the subaddressing
             delimiter.
