### ISSUE TITLE
Make table-postgres / lookup process error handling for query_credentials more robust

### ISSUE THREAD

**Issue by jdelic** [OpenSMTPD/OpenSMTPD#788] opened 2017-05-27 20:23 UTC
I just ran into a problem where I had accidentally removed a query placeholder in `query_credentials`, leading OpenSMTPD to enter an infinite loop on completing `AUTH LOGIN` and becoming unresponsive. This resulted in the following logs:

```
...[snip]...
credentials[10523]: debug: table-postgres: (re)connecting
credentials[10523]: debug: table-postgres: connected
credentials[10523]: warn: table-postgres: trying to reconnect after error: ERROR:  bind message supplies 1 parameters, but prepared statement "stmt6662" requires 0

credentials[10523]: debug: table-postgres: (re)connecting
credentials[10523]: debug: table-postgres: connected
credentials[10523]: warn: table-postgres: trying to reconnect after error: ERROR:  bind message supplies 1 parameters, but prepared statement "stmt6666" requires 0

credentials[10523]: debug: table-postgres: (re)connecting
credentials[10523]: debug: table-postgres: connected
credentials[10523]: warn: table-postgres: trying to reconnect after error: ERROR:  bind message supplies 1 parameters, but prepared statement "stmt6670" requires 0

credentials[10523]: debug: table-postgres: (re)connecting
credentials[10523]: debug: table-postgres: connected
credentials[10523]: warn: table-postgres: trying to reconnect after error: ERROR:  bind message supplies 1 parameters, but prepared statement "stmt6674" requires 0
...[snip]...
```

in an infinite loop. At this point I am not entirely sure what component should make sure that such a lookup query is not repeated indefinitely.

**Comment by poolpOrg** [comment] 2017-05-28 10:27
problem is with table-postgres which should not assume a query error is caused by a connection drop, i'll have a look shortly.

**Comment by jdelic** [comment] 2017-05-28 11:17
> i'll have a look this week as I'm currently swamped.

No worries, let me take a stab at it, should be easy enough to fix :).

**Comment by poolpOrg** [comment] 2017-07-27 13:42
Any progress on fixing this ?

**Comment by poolpOrg** [comment] 2019-08-11 15:18
no feedback since 2016, closing.

**Closed by poolpOrg** 2019-08-11 15:18 UTC
Labels: bug, wait feedback
