### ISSUE TITLE
group ownership of passwd table

### ISSUE THREAD

**Issue by jvolkening** [OpenSMTPD/OpenSMTPD#716] opened 2016-08-17 02:21 UTC
(this is related to a thread on the mailing list)

Running OpenSMTPD 5.7.3p2 on Debian "jessie"

I've been trying to share a passwd file between `opensmtpd` and `dovecot`. I've run into an issue wherein `opensmtpd` will not start if a passwd table referenced in the config is not owned by the `opensmtpd` user's **primary** group. I don't understand why ownership by a secondary group wouldn't work but all of my testing indicates it does not.

I'm not sure whether this is a feature or a bug, or if it has possibly been resolved in more recent releases. Changing the primary group of the `opensmtpd` user to a group shared with dovecot has allowed me to do what I want, but I thought I would post a note here in case this is a bug.

FYI here is the truncated output when trying to start the daemon with **secondary** group ownership:

> ...
mproc: queue -> lka: enabled
mproc: queue -> scheduler: enabled
mproc: queue -> pony: enabled
warn: table-passwd: error parsing config file
warn: table-proc: imsg_read: Connection reset by peer
fatal: table-proc: exiting
...

If the file group owner is changed to the `opensmtpd` **primary** group then everything works as expected.

**Comment by jvolkening** [comment] 2016-08-17 02:56
Sorry - It appears the above behavior is not caused by opensmtpd. I just observed the same thing with dovecot, which complains:

> auth: Error: passwd-file: open(/etc/mail/passwd) failed: Permission denied (euid=112(dovecot) egid=117(dovecot) missing +r perm: /etc/mail/passwd, we're not in group 1004(mail_auth), dir owned by 0:0 mode=0755)

even though the `dovecot` user definitely does have group 1004 as a secondary group. Apparently this has something to do with the difference between Linux primary vs secondary groups as they relate to system daemons.

**Comment by jvolkening** [comment] 2016-08-17 05:29
After further examination/self-education, I'd like to re-open this as a feature request. Would it be possible to have portable opensmtpd call`initgroups()` or something similar after dropping to a regular user in order to inherit the permissions of secondary groups assigned to the daemon user?

**Comment by poolpOrg** [comment] 2016-08-23 11:49
could be possible yes, we'll look into it shortly, there's a hackathon taking place next week to sweep a few open reports ;-)

**Comment by poolpOrg** [comment] 2016-09-02 11:33
any chance you could swing by our irc channel ?

#OpenSMTPD @ freenode

**Comment by poolpOrg** [comment] 2016-09-03 15:55
committed to OpenBSD, this will be synchronized to github today and be part of next snapshots and releases *after* 6.0.0

**Closed by poolpOrg** 2016-09-03 15:55 UTC

**Comment by jvolkening** [comment] 2016-09-05 18:22
Thanks for the quick work! I can't test it yet with my own setup because of problems building the latest '-extras' but will do so as soon as I can.

**Comment by jdelic** [comment] 2016-12-15 00:35
I just stumbled over this issue while working on a [new greylist filter for opensmtpd](https://github.com/jdelic/opensmtpd-filter-greylistd). I can't talk to the filesystem `AF_UNIX` socket opened by `greylistd` since secondary group memberships for `opensmtpd` are not initialized, at least for filters in 6.0.2p1.

@poolpOrg a grep for `initgroups` yields no results on 6.0.2p1... can you give me a pointer how this issue was resolved?

**Comment by poolpOrg** [comment] 2016-12-15 08:56
On Wed, Dec 14, 2016 at 04:35:03PM -0800, jdelic wrote:
> I just stumbled over this issue while working on a [new greylist filter for opensmtpd](https://github.com/jdelic/opensmtpd-filter-greylistd). I can't talk to the filesystem `AF_UNIX` socket opened by `greylistd` since secondary group memberships for `opensmtpd` are not initialized, at least for filters in 6.0.2p1.
> 
> @poolpOrg a grep for `initgroups` yields no results on 6.0.2p1... can you give me a pointer how this issue was resolved?
> 

$ grep SMTPD_VERSION smtpd.h
#define SMTPD_VERSION            "6.0.0"
$ grep initgroups *
lka.c:  if (initgroups(pw->pw_name, pw->pw_gid) ||
$

initgroups() is only used in the lookup process

filters are not supported yet due to a shortcoming that is not trivial
to fix, discussions have taken place to see how much code can be kept
and how much code must be moved/reworked.

as usual, my answer is: you're playing with experimental stuff, you're
on your own ;)


-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by jdelic** [comment] 2016-12-15 10:49
@poolpOrg thanks!

```
$ grep SMTPD_VERSION smtpd.h 
#define SMTPD_VERSION "6.0.0" 
$ grep initgroups * 
lka.c: if (initgroups(pw->pw_name, pw->pw_gid) || 
$
```

Curiously, that specific code is missing from the official 6.0.2p1 tarball from opensmtpd.org. Which is probably why it didn't land in the current Debian Stretch/Testing distribution. Is that by design?

> filters are not supported yet due to a shortcoming that is not trivial to fix, discussions have taken place to see how much code can be kept and how much code must be moved/reworked.

I gathered as much :). Due to a lack of spamd on Linux, it's unfortunately also a very necessary part of OpenSMTPD, shortcomings or not. But I am comfortable compiling against experimental code in this case to get a head start on implementing/testing much needed functionality. What I would appreciate though are some pointers as to what those shortcomings are and how they are being addressed. I would like to participate and help where I can. Is there a mailing list discussion in an archive somewhere? 

> as usual, my answer is: you're playing with experimental stuff, you're on your own ;)

sure, no problem :)
