### ISSUE TITLE
Refuse to start when  OpenSSL and ECDSA certs are used

### ISSUE THREAD

**Issue by freswa** [OpenSMTPD/OpenSMTPD#1050] opened 2020-04-16 00:45 UTC
I tried to run opensmtpd linked against OpenSSL 1.1.1.f.
Build is fine, but at runtime ssl connections fail.

On the server I get
```
smtpd[80338]: 6fdb5e39eec2e385 smtp disconnected reason="io-error: error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib"
```
The client errors with
```
140267326559552:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1543:SSL alert number 80
```

The only reference I could find is [this](https://patchwork.openvpn.net/patch/587/) patchwork of OpenVPN referenced [here](https://community.openvpn.net/openvpn/ticket/1216).

**Comment by dfateyev** [comment] 2020-04-16 12:48
Confirmed, and meanwhile it works fine with "openssl-1.1.1c". A while ago, rebuilt opensmtpd in RHEL7 (epel7) with that version.

**Comment by poolpOrg** [comment] 2020-04-18 18:11
@freswa what system are you using ? what was the latest version of OpenSSL it worked with for you ?

**Comment by freswa** [comment] 2020-04-18 20:19
I am on Arch. I just tried openssl 1.1.1.b up to 1.1.1.f. All those version behave the same way:
TLSv1.2 is fine, TLSv1.3 is broken.
OpenSSL 1.0.x doesn't compile for me.

**Comment by ngortheone** [comment] 2020-04-21 22:52
Debian 10, openssl 1.1.1d-0+deb10u3
I can see TLSv1.3 session happening just fine

```
Apr 21 22:21:52 mail.antonovs.family smtpd[46138]: bcb7e3a39521d277 smtp connected address=46.43.1.242 host=letterbox.kde.org
Apr 21 22:21:52 mail.antonovs.family smtpd[46138]: bcb7e3a39521d277 smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
Apr 21 22:21:53 mail.antonovs.family smtpd[46138]: bcb7e3a39521d277 smtp message msgid=404892f4 size=6992 nrcpt=1 proto=ESMTP
Apr 21 22:21:53 mail.antonovs.family smtpd[46138]: bcb7e3a39521d277 smtp envelope evpid=404892f40b88e492 from=<kde-pim-bounces@kde.org> to=<ihor@antonovs.family>
Apr 21 22:21:53 mail.antonovs.family smtpd[46138]: bcb7e3a434214836 mda delivery evpid=404892f40b88e492 from=<kde-pim-bounces@kde.org> to=<ihor@antonovs.family> rcpt=<ihor@antonovs.family> user=ngor delay=0s result=Ok stat=Delivered
Apr 21 22:21:53 mail.antonovs.family smtpd[46138]: bcb7e3a39521d277 smtp disconnected reason=quit
```

**Comment by freswa** [comment] 2020-04-22 09:48
I checked with
`openssl s_client -debug -host <hostname> -port 587 -starttls smtp -tls1_2` for TLS1.2 and 'openssl s_client -debug -host <hostname> -port 587 -starttls smtp' for TLS1.3

**Comment by ngortheone** [comment] 2020-04-22 10:31
Could it be related to 
https://www.mail-archive.com/openssl-announce@openssl.org/msg00320.html ?

**Comment by freswa** [comment] 2020-04-22 10:42
Just tried 1.1.1.g - doesn't work either.

**Comment by freswa** [comment] 2020-04-22 12:28
I created a Dockerfile and a config to reproduce this issue. Turns out, at least for me this issue only occurs when using ecdsa certs. @poolpOrg stated on IRC, that ecdsa is not supported with OpenSSL at this moment.

**Comment by poolpOrg** [comment] 2020-04-22 12:30
OpenSMTPD does not support ECDSA for OpenSSL at this point, it requires writing a custom ECDSA privsep engine which I did for LibreSSL but not OpenSSL which has a different API:

https://poolp.org/posts/2019-06-02/may-2019-report/

Not a won't fix but this is tricky code and will not make it to the 6.7.0 release, luckily since this only affects portable, I might release a minor portable-only version that adds support for that between 6.7.0 and 6.8.0

**Comment by ngortheone** [comment] 2020-04-22 19:22
@poolpOrg I think that given the above smtpd should refuse to start when ECDSA keys are detected. 
And appropriate error message should be printed.

This will save a lot of time and confusion for many.

**Comment by poolpOrg** [comment] 2020-11-30 22:48
The following branch brings support for ECDSA certs with OpenSSL, please test:

https://github.com/OpenSMTPD/OpenSMTPD/tree/openssl-ecdsa


Here is OpenSMTPD on a Linux system with OpenSSL 1.1.1f and a prime256v1 EC certificate:
```
# smtpd -d
info: OpenSMTPD 6.7.0-portable starting
40e3a533d15366ee smtp connected address=82.65.169.200 host=82-65-169-200.subs.proxad.net
40e3a533d15366ee smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
^C
Exiting
# openssl version
OpenSSL 1.1.1f  31 Mar 2020
#
```

**Comment by freswa** [comment] 2020-12-01 10:16
Works for me

**Comment by poolpOrg** [comment] 2020-12-01 11:09
My sponsor reported a failure which I don't observe so I will take some additional time tracking it down before merging.

I'll close this issue when it's merged in master

**Comment by freswa** [comment] 2020-12-01 11:38
I compiled it with the most recent openssl and now I also get this error on runtime:
`smtpd[85232]: ny express[85232]: c8e2d592794354ef smtp disconnected reason="io-error: error:141C8041:SSL routines:tls_construct_stoc_key_share:malloc failure"`

**Comment by poolpOrg** [comment] 2020-12-01 12:52
This is what I'm tracking, I'm unsure what triggers it at this point but I can't reproduce.

Is this the same setup with just a different OpenSSL ?

**Comment by freswa** [comment] 2020-12-01 12:58
First attempt was a Debian container. The second approach was a ArchLinux system.
So there is more difference between the systems than just OpenSSL. I'll investigate to boil this down to a single change.

**Comment by poolpOrg** [comment] 2020-12-01 17:40
Issue is understood and has been fixed.

I could verify the fix myself, @freswa confirmed on IRC and I'm waiting for a third confirmation from my sponsor before merging to master anytime.

**Comment by poolpOrg** [comment] 2020-12-02 06:56
Confirmed, will merge shortly !

**Comment by poolpOrg** [comment] 2020-12-02 08:20
merged

**Closed by poolpOrg** 2020-12-02 08:20 UTC
Labels: P-High, documentation, improvement
