### ISSUE TITLE
Temporary failure in MX lookup

### ISSUE THREAD

**Issue by yonas** [OpenSMTPD/OpenSMTPD#798] opened 2017-07-22 02:25 UTC
When I try to send mail to anyone, I get a `Temporary failure in MX lookup` error in `/var/log/mail.log`. This effects all emails.

Running `dig mx <doman>` on the server works fine.

Ubuntu 16.04.2 LTS
OpenSMTPD v6.0.2 and v5.7.3

**Comment by poolpOrg** [comment] 2017-07-27 13:16
This is not enough information to debug, please provide log samples.

I'm pretty positive the issue is on your side, if DNS resolution was broken on Ubuntu my mailbox would be filled with user reports by now.

**Comment by yonas** [comment] 2017-07-27 13:20
@poolpOrg I'll try to get logs to you soon. When I replaced OpenSMTPD with Postfix, everything worked properly with the default config, so this is an issue with OpenSMTPD.

**Comment by poolpOrg** [comment] 2017-07-27 18:07
Also, is this coming from a packaged version of OpenSMTPD ?

**Comment by yonas** [comment] 2017-07-29 22:33
@poolpOrg Logs:

```
Jul 29 18:26:53 xxxxxxxxx smtpd[20221]: info: OpenSMTPD 5.7.3p2 starting
Jul 29 18:26:53 xxxxxxxxx smtpd[20226]: info: startup
...
Jul 29 18:27:39 xxxxxxxxx smtpd[20231]: smtp-in: session d1aa3ec3b27dd6b3: connection from host li77-106.members.linode.com [local] established
Jul 29 18:27:39 xxxxxxxxx smtpd[20231]: smtp-in: session d1aa3ec3b27dd6b3: msgid=f38d045f, status=Ok, from=<yonas@xxxxxxxxx.com>, to=<yonas@fizk.net>, size=429, ndest=1, proto=ESMTP
Jul 29 18:27:39 xxxxxxxxx smtpd[20231]: smtp-out: routing: Failed to resolve MX for [relay:fizk.net]: Temporary failure in MX lookup
Jul 29 18:27:39 xxxxxxxxx smtpd[20231]: smtp-out: session 0000000000000000: evpid=f38d045f908d1663, status=TempFail, from=<yonas@xxxxxxxxx.com>, to=<yonas@fizk.net>, rcpt=<->, source=-, relay=fizk.net, delay=0s, stat=Temporary failure in MX lookup
Jul 29 18:27:39 xxxxxxxxx smtpd[20231]: smtp-in: session d1aa3ec3b27dd6b3: connection from host li77-106.members.linode.com [local] closed (client sent QUIT)
```

Yes, this is the packaged version:

```
# apt-cache policy opensmtpd
opensmtpd:
  Installed: 5.7.3p2-1
  Candidate: 5.7.3p2-1
  Version table:
 *** 5.7.3p2-1 500
        500 http://mirrors.linode.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by aikudinov** [comment] 2017-07-30 20:15
Check /etc/resolv.conf just in case.
Could be some weird config with blank resolv.conf, but local dnsmasq would respond to dig, which seems to have localhost fallback.

**Comment by yonas** [comment] 2017-07-30 20:17
@aikudinov I had this at the top:

```
domain members.linode.com
search members.linode.com
nameserver 75.127.97.7
nameserver 45.56.113.178
nameserver 75.127.97.6
```
and 931 lines of this:
```options rotate```

**Comment by yonas** [comment] 2017-07-30 20:20
@aikudinov Wow, the `options rotate` was the issue, thanks! :)

**Comment by yonas** [comment] 2017-07-30 20:21
@poolpOrg This came up after a quick Google search, although I'm not using Redhat:

https://bugzilla.redhat.com/show_bug.cgi?id=841787

**Comment by aikudinov** [comment] 2017-07-30 20:26
None of this servers respond for me, but maybe they do from your host/linode net.
Either way, it works for you now.

**Comment by poolpOrg** [comment] 2017-07-31 08:58
I don't think this is an issue.

Basically what happened is that libasr, upon which OpenSMTPD depends, considers your resolv.conf to be way too large to be a valid resolv.conf and errors out when loading it.

It turns out that libasr was right and your resolv.conf was indeed too large to be a valid resolv.conf due to a glibc bug repeating the same statement hundreds of times over and over. The syntax was valid but clearly the file wasn't and with the glibc bug out of the way, the file would be valid.

I don't really know what should be fixed, we could maybe add a log to mention that libasr failed to parse input ?

**Comment by yonas** [comment] 2017-07-31 09:09
@poolpOrg IMO, ideally libasr would either give a specific error code for that, or an error message saying that resolv.conf was too large to be valid. Then OpenSMTPD would pass that error message to the user via the logs.

**Comment by poolpOrg** [comment] 2017-07-31 09:25
Yes I agree, the behavior should not be fixed, it is correct as is, but there should be a hint given back to the caller (in this case OpenSMTPD) so that logs would pinpoint this.

@ericfaurot ?

**Comment by n8v8R** [comment] 2018-07-21 12:15
ubuntu bionic
kernel 4.17.8
repo Package: opensmtpd (6.0.3p1-1build1) https://packages.ubuntu.com/bionic/opensmtpd

---
```
/etc/resolv.conf
name-servers 127.0.0.1
```
---
> smtpd[85]: smtp-out: Failed to resolve MX for [relay:gmail.com]: Temporary failure in MX lookup
> smtpd[85]: 0000000000000000 mta event=delivery evpid=0ca4513f104ac9a9 from=<root@mail> to=<[obfuscated]@gmail.com> rcpt=<-> source="-" relay="gmail.com" delay=1m15s result="TempFail" stat="Temporary failure in MX lookup"
> smtpd[85]: smtp-out: Failed to resolve MX for [relay:gmail.com]: Temporary failure in MX lookup

---

This seems like a fundamental bug or else how to remedy it?

Monitoring the resolver's log it is apparent that the query for a MX record is not being made.
There are no other issues with DNS resolution for any kind of record on the system

**Comment by poolpOrg** [comment] 2018-09-27 07:09
Since @ericfaurot and I both discussed this in private, I'll add my own opinion for the record:

This is an issue in the resolver layer and it has to be fixed in the libc for OpenBSD and in libasr for other systems. OpenSMTPD can be tagged and released disregarding this issue as updating libasr to a fixed one will automagically fix things without any cooperation from OpenSMTPD code.

I'm closing this issue, @ericfaurot will fix the resolver in OpenBSD and this will be backported to libasr.

**Closed** 2018-09-27 07:09 UTC
Labels: wait feedback
