### ISSUE TITLE
Not authenticated, addresses longer than 31 characters in address

### ISSUE THREAD

**Issue by programacion-web** [OpenSMTPD/OpenSMTPD#582] opened 2015-06-02 16:39 UTC
Hello friends,

When a ser has an address with more than 31 characters, you can not authenticate OpenSMTPD.

```
Jun  2 10:17:27 my-host smtpd[466]: smtp-in: New session 589f42a666311b07 from host my-host.info [78.46.145.206]
Jun  2 10:17:27 my-host smtpd[466]: smtp-in: Started TLS on session 589f42a666311b07: version=TLSv1/SSLv3, cipher=ECDHE-RSA-AES256-SHA, bits=256
Jun  2 10:17:27 my-host smtpd[466]: smtp-in: Failed command on session 589f42a666311b07: "YXV0b2RlZmVuc2FmZW1pbmlzdGFAcmVzaXN0ZW1haWwuY29t" => 501 5.5.2 Syntax error: Syntax error
Jun  2 10:17:27 my-host smtpd[466]: smtp-in: Closing session 589f42a666311b07
```

I have OpenBSD 5.6 and OpenSMTPD 5.4.3

**Comment by poolpOrg** [comment] 2015-06-02 18:05
On Tue, Jun 02, 2015 at 09:39:12AM -0700, Raul Espinosa wrote:
> Hello friends,
> 
> When a ser has an address with more than 31 characters, you can not authenticate OpenSMTPD.
> 
> ```
> Jun  2 10:17:27 my-host smtpd[466]: smtp-in: New session 589f42a666311b07 from host my-host.info [78.46.145.206]
> Jun  2 10:17:27 my-host smtpd[466]: smtp-in: Started TLS on session 589f42a666311b07: version=TLSv1/SSLv3, cipher=ECDHE-RSA-AES256-SHA, bits=256
> Jun  2 10:17:27 my-host smtpd[466]: smtp-in: Failed command on session 589f42a666311b07: "YXV0b2RlZmVuc2FmZW1pbmlzdGFAcmVzaXN0ZW1haWwuY29t" => 501 5.5.2 Syntax error: Syntax error
> Jun  2 10:17:27 my-host smtpd[466]: smtp-in: Closing session 589f42a666311b07
> ```
> 
> I have OpenBSD 5.6 and OpenSMTPD 5.4.3
> 

Hello,

This is fixed in our development branch and will be part of next
major release


-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by programacion-web** [comment] 2015-06-02 20:58
Excuse my ignorance,

As OpenSMTPD comes in OpenBSD by default.
I do not know, as OpenSMTPD upgrade to the latest branch.

Can you help me?

Thank you for development

**Comment by poolpOrg** [comment] 2015-06-03 07:03
Please take questions to the misc@opensmtpd.org list (www.opensmtpd.org/list.html) or to the IRC channel (#OpenSMTPD @ freenode).

Opening tickets on the tracker for user questions makes it harder for us to track what bugs need to be fixed, it also prevents non-developers from answering the question & for the answer to be archived for the next time someone asks the same question.

This is not a bug report, closing.

**Closed by poolpOrg** 2015-06-03 07:03 UTC
