### ISSUE TITLE
fatal: imsg_wait: Connection reset by peer

### ISSUE THREAD

**Issue by src386** [OpenSMTPD/OpenSMTPD#715] opened 2016-08-15 21:01 UTC
Hello,

debian 8
libasr-1.0.2.tar.gz
opensmtpd-201607021504p1.tar.gz

    # LD_LIBRARY_PATH=/usr/local/lib smtpd -vd
    debug: init ssl-tree
    debug: init ca-tree
    debug: init ssl-tree
    debug: using "fs" queue backend
    debug: using "ramqueue" scheduler backend
    debug: using "ram" stat backend
    info: OpenSMTPD 201607021504p1 starting
    fatal: imsg_wait: Connection reset by peer

smtpd.conf : 

    # This is the smtpd server system-wide configuration file.
    # See smtpd.conf(5) for more information.

    # To accept external mail, replace with: listen on all
    listen on localhost

    # If you edit the file, you have to run "smtpctl update table aliases"
    #table aliases file:/etc/mail/aliases

    # Uncomment the following to accept external mail for domain "example.org"
    #accept from any for domain "example.org" alias <aliases> deliver to mbox

    #accept for local alias <aliases> deliver to mbox
    accept for any relay

**Comment by poolpOrg** [comment] 2016-08-23 11:50
Trying to reproduce unsuccessfully but I don't have a Debian 8 available right now.

I'll have a look at it shortly

**Comment by src386** [comment] 2016-08-23 15:02
The debian package (jessie-backports or stretch) is working, they may use a special compilation option, I did not check yet.

**Comment by poolpOrg** [comment] 2016-09-01 11:53
reproduced, we'll have a fix shortly

**Comment by poolpOrg** [comment] 2016-09-01 12:25
issue understood.

Long story short:

We introduced a new fork+reexec model in OpenSMTPD, this took place in a version AFTER the debian package which is why you have no issue with it.

It turns out that fork+reexec is fucked on Linux due to a getopt(3) difference between GNU getopt and the BSD getopt.

We're working on a fix

**Comment by src386** [comment] 2016-09-01 13:58
Thanks.

**Comment by poolpOrg** [comment] 2016-09-02 09:31
Issue was fixed:

https://github.com/OpenSMTPD/OpenSMTPD/commit/fae6a36d4917bfeec881d7f69476f44f8969aefd

The fix will be part of the OpenSMTPD 6.0.0 released planned sometime this week

**Closed by poolpOrg** 2016-09-02 09:31 UTC
