### ISSUE TITLE
Open Relay Check 

### ISSUE THREAD

**Issue by Bob-Belcher** [OpenSMTPD/OpenSMTPD#754] opened 2016-12-22 20:36 UTC
Hi,

i checked a new OpenSMTP setup via openrelay check http://www.mailradar.com/openrelay/ and got the following result - Method 8 and 18 were able to send mail. Is this a config issue? Can I prevent this with an other rule set or is there an issue with the local / handling?

I tried rules like "reject from any for ! local alias <aliases>" without success, these rules give always an syntax error.  Is "!" as mentioned in the man page working?

these are the check results:

```
[Method 8 @ 1482434397]
<<< 220 example.net ESMTP OpenSMTPD
>>> HELO mailradar.com
<<< 250 example.net Hello mailradar.com [193.230.245.6], pleased to meet you
>>> MAIL FROM: <antispam@[xxx.xxx.xxx.xxx]>
<<< 250 2.0.0: Ok
>>> RCPT TO: <"relaytest%mailradar.com">
<<< 250 2.1.5 Destination address valid: Recipient ok
>>> QUIT
<<< 221 2.0.0: Bye
[TEST NOT PASSED]
```

```
[Method 18 @ 1482434408]
<<< 220 example.net ESMTP OpenSMTPD
>>> HELO mailradar.com
<<< 250 example.net Hello mailradar.com [193.230.245.6], pleased to meet you
>>> MAIL FROM: <antispam@[xxx.xxx.xxx.xxx]>
<<< 250 2.0.0: Ok
>>> RCPT TO: <relaytest@mailradar.com@>
<<< 250 2.1.5 Destination address valid: Recipient ok
>>> QUIT
<<< 221 2.0.0: Bye
[TEST NOT PASSED]

```

The version is **5.7.3p2-1~bpo8+1 (debian 8.x)** and this is the configuration:

```
ext_addr = "xxx.xxx.xxx.xxx"
spampd = "smtp://127.0.0.1:10025"

ciphers EECDH+AES128+AESGCM:EECDH+AES256+AESGCM:EECDH+AES128+SHA256:EECDH+AES256+SHA384:EECDH+AES128+SHA:EECDH+AES256+SHA

pki example.net certificate  "/etc/letsencrypt/live/example.net/cert.pem"
pki example.net key          "/etc/letsencrypt/live/example.net/privkey.pem"

table aliases file:/etc/aliases
table creds     passwd:/etc/smtpd/creds
table vdoms     file:/etc/smtpd/vdoms
table vusers    file:/etc/smtpd/vusers

listen on localhost
listen on lo port 10026 tag Filtered
listen on $ext_addr tls hostname example.net auth-optional <creds>
listen on $ext_addr port 465 hostname example.net smtps auth <creds>
listen on $ext_addr port 587 hostname example.net tls-require auth <creds>

accept tagged Filtered virtual <vusers> deliver to maildir
accept from any for domain <vdoms> relay via $spampd

accept for local alias <aliases> deliver to maildir
accept from local for any relay

```

**Comment by poolpOrg** [comment] 2016-12-29 09:26
Can you share your vusers table please ?
I suspect you have a wildcard in there which explains why the tests fail.

In all cases, I can guarantee 100% that these tests that just failed will not do what the tester thinks it will do.

**Comment by poolpOrg** [comment] 2017-02-13 00:36
UP ?

**Comment by poolpOrg** [comment] 2017-02-13 12:41
I can confirm this is an "issue" with your own setup and the content of your virtual maps which trigger a false positive from their scanner. I tried various configurations, including the default one, a simple one and the @opensmtpd.org one which has many virtual domains, relays, etc... and they all result in:

    All tested completed! No relays accepted by remote host!

closing ticket.

**Closed by poolpOrg** 2017-02-13 12:41 UTC

**Comment by ruscur** [comment] 2017-03-06 05:40
Hitting the same issue with no wildcards on 6.0.2p1.  This seems to occur when the RCPT TO doesn't have a domain at the end:

```
 >>> RCPT TO: <relaytest%mailradar.com@>
 >>> RCPT TO: <mailradar.com!relaytest>
 >>> RCPT TO: <"relaytest%mailradar.com">
 >>> RCPT TO: <relaytest@mailradar.com@>
```

Not sure what I could put in my config to prevent this.

**Comment by poolpOrg** [comment] 2017-03-06 07:37
The issue you are hitting is a configuration issue, you need to take this to the mailing list and, most of all, provide your configuration, table contents and logs as you reproduce your problem as this report is essentially useless to troubleshoot anything.

Both a default setup with the default config and my own config with a large number of domains, both primary and virtual, with aliases and redirects to other addresses result in this:

    MAIL FROM:<gilles@poolp.org>
    250 2.0.0: Ok
    RCPT TO: <relaytest%mailradar.com@>
    550 Invalid recipient
    RCPT TO: <mailradar.com!relaytest>
    550 Invalid recipient
    RCPT TO: <"relaytest%mailradar.com">
    550 Invalid recipient
    RCPT TO: <relaytest@mailradar.com@>
    550 Invalid recipient
    QUIT
    221 2.0.0: Bye


There's no way any of these can be accepted unless:

1- there's an *explicit* rule to relay all, which would disregard the part before @
2- there's a catchall accepting all user-parts, since anything else will result in a user-lookup and, unless you have a local system user named "relaytest%mailradar.com", the lookup will fail.

You have a configuration issue and this bug tracker is not the right place to discuss it.
