### ISSUE TITLE
Regression: TLS certificates cause immediate crashes in Portable branch (Docker)

### ISSUE THREAD

**Issue by EmperorArthur** [OpenSMTPD/OpenSMTPD#908] opened 2019-02-20 02:23 UTC
I was unable to run the latest portable branch in a Docker container when using tls.  Fortunately, the latest release (opensmtpd-6.4.1p2) does work.  That's why I've marked this as a regression.

Grepping through the code, the fatal error is called by smtpd.c:205 because `imsg === NULL`.  The debug statement then led me to mproc.c:172 when the pipe is closed.  I've confirmed it's the EV_READ case not the EV_WRITE.  That's as far as I was able to go unfortunately.

# Steps to reproduce
Use the provided smtpd.conf file with an empty '/etc/smtpd/passwd' file, and a valid TLS certificate/key.

## smtpd.conf
> pki_domain = "mail.cd-net.net"
> pki $pki_domain cert "/etc/ssl/private/sites/fullchain.cer"
> pki $pki_domain key  "/etc/ssl/private/sites/site.key"
> 
> table passwords file:/etc/smtpd/passwd
> 
> listen on localhost
> listen on eth0          tls         hostname $pki_domain pki $pki_domain auth-optional <passwords>
> listen on eth0 port 465 smtps       hostname $pki_domain pki $pki_domain auth-optional <passwords>
> listen on eth0 port 587 tls-require hostname $pki_domain pki $pki_domain auth          <passwords>
> 
> action "relay" relay helo $pki_domain
> match auth from any for any action "relay"

## Error Log (run with `-d -v -P mda -T all`)
> debug: init ssl-tree
> info: loading pki information for mail.cd-net.net
> debug: init ca-tree
> debug: init ssl-tree
> info: loading pki keys for mail.cd-net.net
> debug: using "fs" queue backend
> debug: using "ramqueue" scheduler backend
> debug: using "ram" stat backend
> info: OpenSMTPD 6.4.0-portable starting
> debug: init ssl-tree
> info: loading pki information for mail.cd-net.net
> debug: init ca-tree
> debug: init ssl-tree
> info: loading pki keys for mail.cd-net.net
> debug: using "fs" queue backend
> debug: using "ramqueue" scheduler backend
> debug: init ssl-tree
> info: loading pki information for mail.cd-net.net
> debug: init ca-tree
> debug: init ssl-tree
> info: loading pki information for mail.cd-net.net
> debug: init ca-tree
> debug: init ssl-tree
> info: loading pki keys for mail.cd-net.net
> debug: using "fs" queue backend
> debug: using "ramqueue" scheduler backend
> debug: using "ram" stat backend
> setup_peer: queue -> control[7] fd=4
> debug: init ssl-tree
> debug: init ssl-tree
> info: loading pki information for mail.cd-net.net
> debug: init ca-tree
> debug: init ssl-tree
> info: loading pki keys for mail.cd-net.net
> debug: init ssl-tree
> debug: using "ram" stat backend
> setup_peer: lookup -> control[7] fd=4
> debug: init ssl-tree
> info: loading pki keys for mail.cd-net.net
> debug: using "fs" queue backend
> debug: using "ramqueue" scheduler backend
> debug: using "ram" stat backend
> setup_peer: pony express -> control[7] fd=4
> setup_peer: lookup -> pony express[9] fd=5
> setup_peer: lookup -> queue[10] fd=6
> info: loading pki information for mail.cd-net.net
> debug: init ca-tree
> debug: init ssl-tree
> info: loading pki keys for mail.cd-net.net
> debug: using "fs" queue backend
> debug: using "fs" queue backend
> debug: using "ramqueue" scheduler backend
> debug: using "ram" stat backend
> setup_peer: control -> klondike[6] fd=4
> setup_peer: pony express -> klondike[6] fd=5
> setup_peer: queue -> pony express[9] fd=5
> info: loading pki information for mail.cd-net.net
> debug: init ca-tree
> debug: init ssl-tree
> info: loading pki keys for mail.cd-net.net
> debug: using "fs" queue backend
> debug: using "ramqueue" scheduler backend
> debug: using "ram" stat backend
> setup_peer: scheduler -> control[7] fd=4
> setup_peer: scheduler -> queue[10] fd=5
> setup_peer: queue -> lookup[8] fd=6
> debug: using "ramqueue" scheduler backend
> debug: using "ram" stat backend
> setup_peer: klondike -> control[7] fd=4
> setup_peer: control -> lookup[8] fd=5
> setup_peer: pony express -> lookup[8] fd=6
> setup_peer: control -> pony express[9] fd=6
> setup_peer: pony express -> queue[10] fd=7
> setup_peer: klondike -> pony express[9] fd=5
> setup_peer: queue -> scheduler[11] fd=7
> setup_done: ca[6] done
> setup_peer: control -> queue[10] fd=7
> setup_proc: klondike done
> mproc: ca -> control: enabled
> setup_peer: control -> scheduler[11] fd=8
> setup_done: control[7] done
> setup_done: lka[8] done
> setup_proc: lookup done
> mproc: lka -> parent: enabled
> mproc: lka -> queue: enabled
> mproc: lka -> control: enabled
> mproc: lka -> pony: enabled
> mproc: lka -> pony: disabled
> setup_done: pony[9] done
> setup_done: queue[10] done
> setup_done: scheduler[11] done
> smtpd: setup done
> mproc: parent -> control: enabled
> mproc: parent -> lka: enabled
> mproc: parent -> queue: enabled
> mproc: parent -> ca: enabled
> mproc: parent -> pony: enabled
> debug: parent_send_config_ruleset: reloading
> mproc: parent -> lka : 0 IMSG_CONF_START
> mproc: parent -> lka : 0 IMSG_CONF_END
> debug: parent_send_config: configuring pony process
> mproc: parent -> pony : 0 IMSG_CONF_START
> mproc: parent -> pony : 0 IMSG_CONF_END
> debug: parent_send_config: configuring ca process
> mproc: parent -> ca : 0 IMSG_CONF_START
> mproc: parent -> ca : 0 IMSG_CONF_END
> imsg: lka <- parent: IMSG_CONF_START (len=0)
> imsg: lka <- parent: IMSG_CONF_END (len=0)
> TABLE "<anydestination>" backend=static type=LIST
>         "*"
> TABLE "<anyhost>" backend=static type=LIST
>         "0.0.0.0/0"
>         "::/0"
>         "local"
> TABLE "<getpwnam>" backend=getpwnam type=DYNAMIC
> TABLE "<localhost>" backend=static type=LIST
>         "127.0.0.1"
>         "172.17.0.2"
>         "local"
> TABLE "<localnames>" backend=static type=LIST
> setup_proc: scheduler done
>         "127.0.0.1"
> debug: bounce warning after 4h
> mproc: scheduler -> control: enabled
> setup_proc: queue done
> setup_proc: pony express done
> mproc: pony -> parent: enabled
>         "172.17.0.2"
>         "[127.0.0.1]"
>         "[172.17.0.2]"
>         "fc15017187c2"
>         "localhost"
> TABLE "passwords" backend=static type=HASH config="/etc/smtpd/passwd"
> mproc: pony -> queue: enabled
> mproc: pony -> lka: enabled
> mproc: pony -> control: enabled
> mproc: pony -> ca: enabled
> debug: ca_engine_init: using RSA privsep engine
> imsg: pony <- parent: IMSG_CONF_START (len=0)
> queue-backend: queue_init(1) -> 1
> mproc: scheduler -> queue: enabled
> mproc: lka -> pony: enabled
> scheduler: getting batch: mask=0x2f, count=10
> debug: /--- ramqueue: scheduler_ram_batch()
> debug: \---
> scheduler: got r=0, delay=-1, count=10
> scheduler: sleeping
> mproc: ca -> parent: enabled
> mproc: ca -> pony: enabled
> mproc: ca -> pony: disabled
> imsg: ca <- parent: IMSG_CONF_START (len=0)
> imsg: ca <- parent: IMSG_CONF_END (len=0)
> setup_proc: control done
> imsg: pony <- parent: IMSG_CONF_END (len=0)
> debug: smtp: listen on 127.0.0.1 port 25 flags 0x400 pki "" ca ""
> debug: pony: rsae_init
> mproc: queue -> parent: enabled
> debug: init private ssl-tree
> mproc: queue -> control: enabled
> mproc: queue -> lka: enabled
> mproc: queue -> scheduler: enabled
> ramstat: init
> ramstat: set: uptime
> ramstat: uptime: n/a -> n/a
> mproc: queue -> pony: enabled
> mproc: control -> scheduler: enabled
> mproc: control -> queue: enabled
> mproc: control -> parent: enabled
> mproc: control -> lka: enabled
> mproc: control -> pony: enabled
> mproc: control -> ca: enabled
> queue-backend: queue_envelope_walk() -> -1 (0000000000000000)
> debug: queue: done loading queue into scheduler
> debug: parent -> ca: pipe closed
> smtpd: process ca socket closed
>

**Comment by poolpOrg** [comment] 2019-02-20 07:00
awww damn, this looks like a portable-specific issue as I'm not experiencing this on native :-/

I will investigate today, thanks for the report :+1:

**Comment by poolpOrg** [comment] 2019-02-20 12:05
Care to give it another run ?

A few commits had not been synchronized with github yet and one is likely to actually fix your issue :-)

**Comment by EmperorArthur** [comment] 2019-02-21 03:25
Still broken unfortunately.

Pull #911 should let you use Docker Hub as a CI platform for this issue.  Especially if the "Internal and external pull requests" option is triggered and you create a PR to test things.

**Comment by poolpOrg** [comment] 2019-02-21 09:03
ok, bad news for me but good that you're making it easier to reproduce ;-)

**Comment by ngortheone** [comment] 2019-10-11 16:05
@EmperorArthur it looks like it could be related to https://github.com/OpenSMTPD/OpenSMTPD/issues/944

I got docker build working with this fix https://github.com/OpenSMTPD/OpenSMTPD/pull/945

**Comment by ngortheone** [comment] 2019-11-02 00:34
This looks like https://github.com/OpenSMTPD/OpenSMTPD/issues/958
It is a shame that we did not catch this sooner.

Good news @EmperorArthur  is that this issues is on track to get fixed.
Closing this one as a duplicate of https://github.com/OpenSMTPD/OpenSMTPD/issues/958

**Closed** 2019-11-02 00:34 UTC
