### ISSUE TITLE
AUTH failures in table-mysql and possibly other -extras requires restarting smtpd

### ISSUE THREAD

**Issue by edgarpettijohn** [OpenSMTPD/OpenSMTPD#928] opened 2019-08-10 22:22 UTC
Please see post to misc@opensmtpd.org on 21 Jul 2019 for full details.

Periodic authentication failures requires restarting smtpd.

**Comment by poolpOrg** [comment] 2019-08-18 15:36
I took the liberty of rewording the issue synopsis because it was very alarmist and made it sound far more critical than it really:

- stock OpenSMTPD does not require restart upon AUTH failures
- various auth backends do not require restart upon AUTH failures either

You are experincing this with the MySQL backend, a similar issue happened in the past with the PostgreSQL backend but it was fixed and therefore the issue does not exist there anymore.

AFAIK, only table-mysql is affected.

**Comment by ngortheone** [comment] 2019-11-03 00:31
Is this something that waits table API rewrite to get fixed?

**Comment by poolpOrg** [comment] 2019-11-03 03:17
Yes, the mysql-backend might just get rewritten from scratch for the new API.

@edgarpettijohn can you test building with the following change ? it is not the correct fix but may fix your issue while highlighting the real cause.

[table_mysql.diff.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/3801192/table_mysql.diff.txt)

**Comment by Pettijohne** [comment] 2019-11-04 02:02
After running the patch for close to 24 hours I haven't seen any issues. Previously I would have had to restart the daemon at least once in this time frame.

**Comment by poolpOrg** [comment] 2019-11-04 02:56
Did you see error logs though ?

**Comment by Pettijohne** [comment] 2019-11-04 13:23
On Nov 3, 2019 8:56 PM, Gilles Chehade <notifications@github.com> wrote:
>
> Did you see error logs though ?
>

I didn't. I'll give it a couple days and grep through the logs and see.

Thanks,

Edgar

**Comment by poolpOrg** [comment] 2019-11-06 18:23
ping ?

**Comment by Pettijohne** [comment] 2019-11-06 22:20
I don't see anything in the logs. Just reverted back to the pre-patched version. Is it possible the issue was fixed on the mariadb side and the patch not necessary?

**Comment by poolpOrg** [comment] 2019-11-06 23:38
No idea but if you can no longer reproduce in several days when the issue required at least a restart a day, maybe an update of either one of opensmtpd, mariadb or libmysqlclient has made the issue go away ?

My opinion is that we should close this ticket because table-mysql will be rewritten in a few months and unless you manage to reproduce with the current version, I won't spend time trying to understand why it has failed and no longer does.

If you experience the issue again, you may just reopen it and we assess again.

**Closed** 2019-11-16 11:08 UTC
Labels: regression, wait feedback
