### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by antoniotvr** [OpenSMTPD/OpenSMTPD#1056] opened 2020-04-25 13:53 UTC
Hi. 

I have installed opensmtpd on Fedora server (to have always latest version) but no log file is produced in /var/log.

Searching online seems that the software do Not produce any log file to see what It Is happening with SMTP in real time. 

It Is possibile to activate a log file with useful information such as that can be seen when the tool is started from command line with options (-dv)? 

Thank you

**Comment by whataboutpereira** [comment] 2020-04-25 14:26
Redhat usually logs to /var/log/maillog. I suspect Fedora should do the same.

**Comment by antoniotvr** [comment] 2020-04-25 17:55
Yes it should do It. 

But it doesn't. 

How can i specify the log file and the log level? 

Regards

**Comment by whataboutpereira** [comment] 2020-04-25 20:31
Are you building it yourself?

**Comment by ngortheone** [comment] 2020-04-26 03:01
On linux systems with systemd (Fedora is one of them) I would check the journal first.

This is how it works for me on Debian
```sh
journalctl -u opensmtpd.service --since '1 day ago'
```

Check your `opensmtpd.service`(might be called a bit differently) unit file. It is possible that the smtpd is started with `-d` option and logs to stdout (which is captured by systemd)

**Comment by antoniotvr** [comment] 2020-04-26 10:53
> Are you building it yourself?

No it is the standard package provided by the distro.

**Comment by antoniotvr** [comment] 2020-04-26 10:55
> On linux systems with systemd (Fedora is one of them) I would check the journal first.
> 
> This is how it works for me on Debian
> ```sh
> journalctl -u opensmtpd.service --since '1 day ago'
> ```
> 
> Check your `opensmtpd.service`(might be called a bit differently) unit file. It is possible that the smtpd is started with `-d` option and logs to stdout (which is captured by systemd)

Ok thank you. 

I will try this as you have indicated.

And i will check the unit file of systemd service to see if there is the -d option. 

I let You Know. 

Thank you

**Comment by dfateyev** [comment] 2020-04-26 22:12
Fedora / EPEL opensmtpd package maintainer here.
As pointed above, you should utilize systemd journal functionality: `"journalctl -xeu opensmtpd"` or similar (depends on which log time period you're interested in).
You can also check the latest daemon messages and status with `"systemctl status opensmtpd -l"`.

**Comment by antoniotvr** [comment] 2020-04-27 04:58
Perfect, thank you for your detailed explanation.

**Comment by poolpOrg** [comment] 2020-04-29 22:39
not a bug, closing the ticket :-)

**Closed by poolpOrg** 2020-04-29 22:39 UTC
