### ISSUE TITLE
Errors related to TLS with OpenSMTPD 6.4.0p1 (incl. segfault)

### ISSUE THREAD

**Issue by Ekleog** [OpenSMTPD/OpenSMTPD#886] opened 2018-11-05 14:02 UTC
Two errors have been reported in what appears to be things related to TLS handling.

#### First error

First one is OpenSMTPD exiting with exit code 1 on startup when being passed a PKI. Details including full logs are at https://github.com/NixOS/nixpkgs/pull/48901#issuecomment-435838142 and comments below. The reporter confirmed via IRC that this appeared both with `libressl_2_7` (our default) and `libressl_2_8` (after I made them try it).

#### Second error

The second one was reported only via IRC so no link to a previous issue here. It is a segfault that looks pretty much like jumping into the stack (IP and SP being way too close for my taste) when trying to send a mail to GMail over TLS, with apparently perfect reproducibility. The logs are at https://gist.github.com/the-kenny/179d82cbea1c45acf67285ba935297e4.
It has also been tested with `libressl` 2.7 and 2.8.

#### Precisions about the build system

Our OpenSMTPD is built with the following two patches, that I don't think should be relevant to the error at play: [(1)](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/mail/opensmtpd/fix-build.diff) and [(2)](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/mail/opensmtpd/proc_path.diff). We also substitude `/usr/libexec` with the appropriate path [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/mail/opensmtpd/default.nix#L25-L26), and remove `chgrp` / `chmod 2555` from `make install`, that aren't possible in our sandboxed build system.

The `libressl` dependency defaults to `2.7.4`, and has been tested for the two issues to reproduce with `2.8.2`.
The other dependencies we pass are currently `libasr-1.0.2`, `libevent-2.1.8`, `zlib-1.2.11`, `bdb-5.3.28` and `linux-pam-1.3.0`.

Do you have any idea what this might be due to?

**Comment by the-kenny** [comment] 2018-11-05 14:05
It's me who reported the second error - feel free to ping me if you need any more information or a more complete log output :)

**Comment by poolpOrg** [comment] 2018-11-05 14:10
No idea but we'll investigate.

Can you provide the configure output as well as the configure.log ?

Gilles

**Comment by Izorkin** [comment] 2018-11-05 14:20
My configure:
```
pki mail.example.com cert "/etc/ssl/private/mail.example.com.crt"
pki mail.example.com key "/etc/ssl/private/mail.example.com.key"
ca mail.example.com cert "/etc/ssl/certs/ca-bundle.crt"
listen on 0.0.0.0 tls pki mail.example.com ca mail.example.com
action "local" mbox
match from local for local action "local"
```
error - https://github.com/NixOS/nixpkgs/pull/48901#issuecomment-435838142

**Comment by poolpOrg** [comment] 2018-11-05 14:51
@Izorkin care to show me the output of:

    $ openssl x509 -in /etc/ssl/private/mail.example.com.crt -text -noout| grep Algorithm

**Comment by Izorkin** [comment] 2018-11-05 14:53
@poolpOrg 
```
    Signature Algorithm: sha256WithRSAEncryption
            Public Key Algorithm: rsaEncryption
    Signature Algorithm: sha256WithRSAEncryption

```

**Comment by the-kenny** [comment] 2018-11-05 16:48
Relevant parts from my config (it crashes when a mail is matched to the `action_gmail` relay:

```
        listen on 0.0.0.0

        table secrets file:/etc/...

        action action_maildir    maildir "~/.mail/local"
        action action_gmail relay host smtp+tls://tarn-vedra@smtp.gmail.com:587 auth <secrets>

        match from local for any action action_gmail
```

**Comment by memiks** [comment] 2018-11-06 13:22
Hello,

I have the same issue with alpine and pki


I attached my config, strace, start log.
[smtpd.log](https://github.com/OpenSMTPD/OpenSMTPD/files/2553290/smtpd.log)
[strace.log](https://github.com/OpenSMTPD/OpenSMTPD/files/2553291/strace.log)
[smtpd.conf](https://github.com/OpenSMTPD/OpenSMTPD/files/2553293/smtpd.conf.log)

this is the algorithm grep on certificate :
    Signature Algorithm: sha256WithRSAEncryption
            Public Key Algorithm: rsaEncryption
    Signature Algorithm: sha256WithRSAEncryption


If I remove pki lines all works fine.

BR.

**Comment by poolpOrg** [comment] 2018-11-06 15:00
What version of LibreSSL are you using ?

Gilles

**Comment by poolpOrg** [comment] 2018-11-06 15:19
OK, I can reproduce and I have a fix but considering the bug I'm unsure if this is an issue with OpenSMTPD which would require to release opensmtpd-6.4.0p2 or an issue with LibreSSL which would require them to release a new version, will get back to you.

**Comment by poolpOrg** [comment] 2018-11-06 16:19
Guys, care to try the following diff ?

https://www.poolp.org/~gilles/freezero.diff

**Comment by Ekleog** [comment] 2018-11-06 16:48
@the-kenny @Izorkin In case it can help you test more easily, the following overlay does the job:
```nix
self: super:
rec {
  opensmtpd = super.opensmtpd.overrideAttrs (a: {
    patches = a.patches ++ [
      (builtins.fetchurl {
        url = "https://www.poolp.org/~gilles/freezero.diff";
        sha256 = "1mgsi97hypf7p14mq38a7kx7c7dx4wwqqirban84s8p3cgy9l0xh";
      })
    ];
  });
}
```

I can confirm the patch doesn't break our automated test, but the test doesn't check TLS, so… will let @Izorkin and @the-kenny test :)

**Comment by poolpOrg** [comment] 2018-11-06 16:56
I have verified both outgoing and incoming TLS and the issue is gone as far as I'm concerned, if you guys can confirm on your own I'll publish a patch-level release tonight.

**Comment by usonianhorizon** [comment] 2018-11-06 17:58
I have been running OpenSMTPD under Ubuntu 16.04 LTS, and just this morning upgraded our server to 18.04.1 LTS.  Well, that might have been a mistake since all outbound email attempts crash the opensmtpd.service.  I realize that I am resigned to a lagging version from the Ubuntu package repository but still this seems to be a critical issue.

` smtpd -h
version: OpenSMTPD 6.0.3-portable`

I *believe* that I am facing this problem, but am unsure, and I don't know what would be the best solution in order to extricate myself from this as we are stuck.

This is the error when sending from Mutt:

`msmtp: cannot read from TLS connection: The TLS connection was non-properly terminated.
msmtp: could not send mail (account default from /home/pavneet/.msmtprc)`

Roundcube and other clients also result in OpenSMTPD crashing at this point.

I can certainly post more debugging information if you guide me to what is useful.

advTHANKSance.

**Comment by poolpOrg** [comment] 2018-11-06 18:07
@usonianhorizon I doubt this is related to this issue, is the libssl on your system LibreSSL ?

**Comment by Izorkin** [comment] 2018-11-06 18:16
@poolpOrg Thanks, patch worked.

**Comment by poolpOrg** [comment] 2018-11-06 18:18
I knew but I wanted an ack from you before closing this ticket ;-)

**Closed by poolpOrg** 2018-11-06 18:18 UTC

**Comment by usonianhorizon** [comment] 2018-11-06 18:30
<WILCO>

**Comment by the-kenny** [comment] 2018-11-06 20:33
I can also confirm that the above patch fixes all issues for me :) Thanks!
