### ISSUE TITLE
`from any` rules never matched by IPv6 sources in 6.6.0p1

### ISSUE THREAD

**Issue by ArchangeGabriel** [OpenSMTPD/OpenSMTPD#969] opened 2019-11-01 21:12 UTC
Following some tests I ran the last two days in order to understand issues, it appeared to me that I’m getting `550 Invalid recipient:` for any email that should be matched by a `from any` rule. The affected excerpts from [my config](https://github.com/OpenSMTPD/OpenSMTPD/issues/958#issuecomment-548623601) are the following ones:

```
# Deliver incoming emails (that passed rDNS test) for local users
action "inbox" lmtp "/var/run/dovecot/lmtp" rcpt-to virtual <vusers>
match from any for domain <vdoms> action "inbox"

# Send outgoing emails to DKIM
action "dkim" relay host smtp://127.0.0.1:10027
match auth from any for any action "dkim"
```

This works perfectly well in 6.4.xpy, but both are never matched in 6.6.0p1.

Interestingly, replacing `from any` by `from rdns` (in 6.6.0p1) in the first one works (though is prone to [other issues](https://github.com/OpenSMTPD/OpenSMTPD/issues/968)).

**Comment by ArchangeGabriel** [comment] 2019-11-01 21:17
Log of a message from outside (supposed to match the first rule):
```
3062e7d5c541e019 smtp connected address=[2a00:1450:4864:20::42f] host=mail-wr1-x42f.google.com
mproc: pony -> lka: realloc 128 -> 256
mproc: pony -> lka : 135 IMSG_REPORT_SMTP_LINK_CONNECT
smtp: 0xee8776b97c0: >>> 220 heloname ESMTP OpenSMTPD
mproc: pony -> lka : 73 IMSG_REPORT_SMTP_PROTOCOL_SERVER
mproc: pony -> lka : 53 IMSG_??? (128)
smtp: 0xee8776b97c0: IO_LOWAT <io:0xee877720f10 fd=21 to=300000 fl=W ib=0 ob=0>
imsg: lka <- pony: IMSG_REPORT_SMTP_LINK_CONNECT (len=135)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=73)
imsg: lka <- pony: IMSG_??? (128) (len=53)
smtp: 0xee8776b97c0: IO_DATAIN <io:0xee877720f10 fd=21 to=300000 fl=R ib=31 ob=0>
smtp: 0xee8776b97c0: <<< EHLO mail-wr1-x42f.google.com
mproc: pony -> lka : 64 IMSG_REPORT_SMTP_PROTOCOL_CLIENT
mproc: pony -> lka : 65 IMSG_??? (129)
smtp: 0xee8776b97c0: STATE_CONNECTED -> STATE_HELO
smtp: 0xee8776b97c0: >>> 250-heloname Hello mail-wr1-x42f.google.com [2a00:1450:4864:20::42f], pleased to meet you
mproc: pony -> lka : 134 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: >>> 250-8BITMIME
mproc: pony -> lka : 47 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: >>> 250-ENHANCEDSTATUSCODES
mproc: pony -> lka : 58 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: >>> 250-SIZE 36700160
mproc: pony -> lka : 52 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: >>> 250-DSN
mproc: pony -> lka : 42 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: >>> 250-STARTTLS
mproc: pony -> lka : 47 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: >>> 250 HELP
mproc: pony -> lka : 43 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: IO_LOWAT <io:0xee877720f10 fd=21 to=300000 fl=W ib=0 ob=0>
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_CLIENT (len=64)
imsg: lka <- pony: IMSG_??? (129) (len=65)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=134)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=47)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=58)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=52)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=42)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=47)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=43)
smtp: 0xee8776b97c0: IO_DATAIN <io:0xee877720f10 fd=21 to=300000 fl=R ib=10 ob=0>
smtp: 0xee8776b97c0: <<< STARTTLS
mproc: pony -> lka : 43 IMSG_REPORT_SMTP_PROTOCOL_CLIENT
smtp: 0xee8776b97c0: >>> 220 2.0.0 Ready to start TLS
mproc: pony -> lka : 63 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: STATE_HELO -> STATE_TLS
smtp: 0xee8776b97c0: IO_LOWAT <io:0xee877720f10 fd=21 to=300000 fl=W ib=0 ob=0>
mproc: pony -> lka : 24 IMSG_CERT_INIT
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_CLIENT (len=43)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=63)
imsg: lka <- pony: IMSG_CERT_INIT (len=24)
debug: looking up pki "heloname"
mproc: lka -> pony: realloc 128 -> 4096
mproc: lka -> pony : 3949 IMSG_CERT_INIT
imsg: pony <- lka: IMSG_CERT_INIT (len=3949)
debug: session_start_ssl: switching to SSL
debug: pony: rsae_priv_enc
mproc: pony -> ca: realloc 0 -> 128
mproc: pony -> ca: realloc 128 -> 1024
mproc: pony -> ca : 563 IMSG_CA_RSA_PRIVENC (flush)
imsg: ca <- pony: IMSG_CA_RSA_PRIVENC (len=563)
mproc: ca -> pony: realloc 0 -> 128
mproc: ca -> pony: realloc 128 -> 1024
mproc: ca -> pony : 532 IMSG_CA_RSA_PRIVENC
imsg: pony <- ca: IMSG_CA_RSA_PRIVENC (len=532)
smtp: 0xee8776b97c0: IO_TLSREADY <io:0xee877720f10 fd=21 to=300000 fl=R tls=TLSv1.3:TLS_AES_256_GCM_SHA384:256 ib=0 ob=0>
3062e7d5c541e019 smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
mproc: pony -> lka : 69 IMSG_REPORT_SMTP_LINK_TLS
smtp: 0xee8776b97c0: smtp_cert_verify_cb: no-client-cert
mproc: pony -> control : 42 IMSG_STAT_INCREMENT
smtp: 0xee8776b97c0: STATE_TLS -> STATE_HELO
smtp: 0xee8776b97c0: IO_DATAIN <io:0xee877720f10 fd=21 to=300000 fl=R tls=TLSv1.3:TLS_AES_256_GCM_SHA384:256 ib=31 ob=0>
smtp: 0xee8776b97c0: <<< EHLO mail-wr1-x42f.google.com
mproc: pony -> lka : 64 IMSG_REPORT_SMTP_PROTOCOL_CLIENT
mproc: pony -> lka : 65 IMSG_??? (129)
smtp: 0xee8776b97c0: STATE_HELO -> STATE_HELO
smtp: 0xee8776b97c0: >>> 250-heloname Hello mail-wr1-x42f.google.com [2a00:1450:4864:20::42f], pleased to meet you
mproc: pony -> lka : 134 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: >>> 250-8BITMIME
mproc: pony -> lka : 47 IMSG_REPORT_SMTP_PROTOCOL_SERVER
imsg: lka <- pony: IMSG_REPORT_SMTP_LINK_TLS (len=69)
imsg: control <- pony: IMSG_STAT_INCREMENT (len=42)
smtp: 0xee8776b97c0: >>> 250-ENHANCEDSTATUSCODES
ramstat: increment: smtp.tls
mproc: pony -> lka : 58 IMSG_REPORT_SMTP_PROTOCOL_SERVER
ramstat: smtp.tls (0x5bf4974c61): 0 -> 1
smtp: 0xee8776b97c0: >>> 250-SIZE 36700160
mproc: pony -> lka : 52 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: >>> 250-DSN
mproc: pony -> lka : 42 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: >>> 250 HELP
mproc: pony -> lka : 43 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: IO_LOWAT <io:0xee877720f10 fd=21 to=300000 fl=W tls=TLSv1.3:TLS_AES_256_GCM_SHA384:256 ib=0 ob=0>
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_CLIENT (len=64)
imsg: lka <- pony: IMSG_??? (129) (len=65)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=134)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=47)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=58)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=52)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=42)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=43)
smtp: 0xee8776b97c0: IO_DATAIN <io:0xee877720f10 fd=21 to=300000 fl=R tls=TLSv1.3:TLS_AES_256_GCM_SHA384:256 ib=48 ob=0>
smtp: 0xee8776b97c0: <<< MAIL FROM:<bruno.n.pagani@gmail.com> SIZE=5088
mproc: pony -> lka : 81 IMSG_REPORT_SMTP_PROTOCOL_CLIENT
debug: smtp: SIZE in MAIL FROM command
mproc: pony -> queue: realloc 0 -> 128
mproc: pony -> queue : 8 IMSG_SMTP_MESSAGE_CREATE
imsg: queue <- pony: IMSG_SMTP_MESSAGE_CREATE (len=8)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_CLIENT (len=81)
queue-backend: queue_message_create() -> 1 (3fb34f18)
mproc: queue -> pony: realloc 0 -> 128
mproc: queue -> pony : 16 IMSG_SMTP_MESSAGE_CREATE
imsg: pony <- queue: IMSG_SMTP_MESSAGE_CREATE (len=16)
mproc: pony -> lka : 37 IMSG_REPORT_SMTP_TX_BEGIN
smtp: 0xee8776b97c0: >>> 250 2.0.0 Ok
mproc: pony -> lka : 67 IMSG_??? (134)
mproc: pony -> lka : 47 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: IO_LOWAT <io:0xee877720f10 fd=21 to=300000 fl=W tls=TLSv1.3:TLS_AES_256_GCM_SHA384:256 ib=0 ob=0>
imsg: lka <- pony: IMSG_REPORT_SMTP_TX_BEGIN (len=37)
imsg: lka <- pony: IMSG_??? (134) (len=67)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=47)
smtp: 0xee8776b97c0: IO_DATAIN <io:0xee877720f10 fd=21 to=300000 fl=R tls=TLSv1.3:TLS_AES_256_GCM_SHA384:256 ib=30 ob=0>
smtp: 0xee8776b97c0: <<< RCPT TO:<someuser@domain>
mproc: pony -> lka : 63 IMSG_REPORT_SMTP_PROTOCOL_CLIENT
mproc: pony -> lka: realloc 256 -> 512
mproc: pony -> lka : 301 IMSG_SMTP_EXPAND_RCPT
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_CLIENT (len=63)
imsg: lka <- pony: IMSG_SMTP_EXPAND_RCPT (len=301)
expand: 0xf3981d58678: expand_insert() called for address:someuser@domain[parent=(nil), rule=(nil)]
expand: 0xf3981d58678: inserted node 0xf3981d5a370
expand: lka_expand: address: someuser@domain [depth=0]
lookup: match "[2a00:1450:4864:20::42f]" as NETADDR in table static:<localhost> -> false
lookup: match "[2a00:1450:4864:20::42f]" as NETADDR in table static:<anyhost> -> false
lookup: match "" as STRING in table static:<dynamic:0> -> false
lookup: match "[2a00:1450:4864:20::42f]" as NETADDR in table static:<anyhost> -> false
no rule matched
mproc: lka -> pony : 35 IMSG_SMTP_EXPAND_RCPT
expand: 0xf3981d58678: clearing expand tree
imsg: pony <- lka: IMSG_SMTP_EXPAND_RCPT (len=35)
smtp: 0xee8776b97c0: >>> 550 Invalid recipient: <someuser@domain>
mproc: pony -> lka : 61 IMSG_??? (135)
3062e7d5c541e019 smtp failed-command command="RCPT TO:<someuser@domain>" result="550 Invalid recipient: <someuser@domain>"
mproc: pony -> lka : 78 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: IO_LOWAT <io:0xee877720f10 fd=21 to=300000 fl=W tls=TLSv1.3:TLS_AES_256_GCM_SHA384:256 ib=0 ob=0>
imsg: lka <- pony: IMSG_??? (135) (len=61)
imsg: lka <- pony: IMSG_REPORT_SMTP_PROTOCOL_SERVER (len=78)
smtp: 0xee8776b97c0: IO_DATAIN <io:0xee877720f10 fd=21 to=300000 fl=R tls=TLSv1.3:TLS_AES_256_GCM_SHA384:256 ib=6 ob=0>
smtp: 0xee8776b97c0: <<< QUIT
mproc: pony -> lka : 39 IMSG_REPORT_SMTP_PROTOCOL_CLIENT
smtp: 0xee8776b97c0: >>> 221 2.0.0 Bye
mproc: pony -> lka : 48 IMSG_REPORT_SMTP_PROTOCOL_SERVER
smtp: 0xee8776b97c0: STATE_HELO -> STATE_QUIT
smtp: 0xee8776b97c0: IO_LOWAT <io:0xee877720f10 fd=21 to=300000 fl=W tls=TLSv1.3:TLS_AES_256_GCM_SHA384:256 ib=0 ob=0>
3062e7d5c541e019 smtp disconnected reason=quit
```

**Comment by ArchangeGabriel** [comment] 2019-11-01 21:23
And for an outgoing message:
```
ff66848218f51f17 smtp connected address=[mylaptopIPv6] host=rDNSname
debug: looking up pki "heloname"
debug: session_start_ssl: switching to SSL
debug: pony: rsae_priv_enc
ff66848218f51f17 smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
smtp: 0x1200bbb1f80: smtp_cert_verify_cb: no-client-cert
debug: lka: authenticating for passwd:username
ff66848218f51f17 smtp authentication user=username result=ok
debug: smtp: SIZE in MAIL FROM command
no rule matched
ff66848218f51f17 smtp failed-command command="RCPT TO:<bruno.n.pagani@gmail.com>" result="550 Invalid recipient: <bruno.n.pagani@gmail.com>"
ff66848218f51f17 smtp disconnected reason=quit
```

**Comment by whataboutpereira** [comment] 2019-11-01 21:24
IPv6 issue?

**Comment by ArchangeGabriel** [comment] 2019-11-01 21:28
Looks a plausible hypothesis based on the above sample. Then I should try with some non-IPv6 provider and on my sender end remove my IPv6 before testing. Unless there is some way to tell OpenSMTPD to listen only on v4 addresses?

**Comment by whataboutpereira** [comment] 2019-11-01 21:32
listen on <interface> inet4 perhaps.

https://man.openbsd.org/smtpd.conf

**Comment by ArchangeGabriel** [comment] 2019-11-01 22:20
Bingo, adding `inet4` to both listening rules made it work. Changed the title accordingly.

**Comment by poolpOrg** [comment] 2019-11-02 04:21
This is not true for the native version where Gmail will contact me over IPv6 and match a `from any`, so this may be a problem either in the portable layer or in the delta between the native and the portable version since there are a few differences wrt ipv6.

**Comment by poolpOrg** [comment] 2019-11-02 04:35
Confirmed, the same config will work on OpenBSD but not in portable.

I can reproduce and should have a fix shortly.

**Comment by poolpOrg** [comment] 2019-11-02 05:04
Long story short, some systems have a "broken" inet_pton() function which do not support inet6. For these systems, we ship a broken_inet_pton_inet6() function which does what the system function should do and we fallback to it if the system's inet_pton() fails with the proper errno.

Between 6.4 and 6.6, a cleanup of the inet6 code was done in OpenBSD's version of OpenSMTPD which does not have this piece of code and a regression was introduced during the merge of the OpenBSD version to the portable version because the broken_inet_pton_inet6() function is used on the wrong source input after the merge.

Issue is fixed in portable branch now.

**Closed by poolpOrg** 2019-11-02 05:04 UTC
Labels: regression

**Comment by ArchangeGabriel** [comment] 2019-11-03 15:11
Thanks for fixing this issue and providing a detailed analysis of why it happened. ;)
