### ISSUE TITLE
Feature Request: Dual Delivery

### ISSUE THREAD

**Issue by korylprince** [OpenSMTPD/OpenSMTPD#791] opened 2017-06-09 20:23 UTC
I recently stumbled upon OpenSMTPD after searching for an alternative to the configuration nightmare which is postfix. I love the simple configuration (it seems very similar to pf.)

The one problem I have is I need dual delivery (for archiving purposes.) I've searched the internet for many hours and could not find a way to do dual delivery, at least for generic, unknown recipients.

I don't know the best way to accomplish this, but I envision just being able to use multiple delivery actions in a rule; Something like:

`accept from any for any relay via ... , relay via ...`

I see in issue #772 that you may be separating the action from the decision in rules. If that is happening anyways, perhaps you could allow multiple actions to be applied.

If there is any way to do dual delivery now, I'd love to hear your ideas.

**Comment by jdelic** [comment] 2017-06-09 22:43
@korylprince 

I agree that it might be useful to have multiple rules apply to an email. Like in qmail (the other MTA that I am familiar with), your *particular use-case* seems to really belong in the LDA part. Specifically, to achieve what you want, you could

  * use a `.forward` file with two delivery instructions for particular users or more generically for all users
  * with `dovecot-lda` or dovecot's LMTP server, for example, use the Sieve language plug-in and the [copy extension](https://wiki.dovecot.org/Pigeonhole/Sieve)

Procmail would also easily achieve what you're looking for.

**Comment by korylprince** [comment] 2017-06-12 13:31
Unfortunately, none of the email through this server is delivered locally. This server acts like an internal relay, relaying mail from local devices (server notifications, Xerox scans, etc) to Google's relay and relaying mail back and forth from our internal helpdesk system to Google's system. (We use GSuite/Google Apps.)

All of this mail has to be archived, but none of it is delivered locally where it could be processed by LDA rules.

Unless anyone else has a suggestion, I guess I will relay mail through a local postfix instance with the always_bcc option and then back out through OpenSMTPD.

Not really what I want to do, but hopefully such an option will be added to OpenSMTPD and I can remove Postfix from the mix.

**Comment by edgarpettijohn** [comment] 2017-06-18 22:16
What is your current smtpd.conf?

**Comment by korylprince** [comment] 2017-06-20 18:56
My current smtpd.conf (with postfix as the copying middleman) is:
```ini
# credentials
table relay_credentials file:/etc/opensmtpd/relay_credentials
table auth_credentials file:/etc/opensmtpd/auth_credentials

# ssl
pki ubuntu-smtp.example.com certificate "/etc/ssl/chained.crt"
pki ubuntu-smtp.example.com key "/etc/ssl/private/server.key"

# relays - use source { 0.0.0.0 } to skip trying IPv6
relay_gsuite = "relay via tls+auth://google@smtp-relay.gmail.com:587 auth <relay_credentials> source { 0.0.0.0 } verify"
relay_archive = "relay via tls://archiver.example.com verify"
relay_helpdesk = "relay via tls://ubuntu-helpdesk.example.com verify"
relay_pickup = "relay via smtp://localhost:2530"

# internal network
listen on 0.0.0.0 port 25 tls tag internal
listen on 0.0.0.0 port 587 tls-require auth <auth_credentials> tag internal_authenticated

table servers file:/etc/opensmtpd/servers
table legacy file:/etc/opensmtpd/legacy

accept tagged internal from source <servers> for any $relay_pickup
accept tagged internal from source <legacy> for any $relay_pickup
accept tagged internal_authenticated from any for any $relay_pickup


# public network
listen on 0.0.0.0 port 2525 tls-require tag incoming
listen on 0.0.0.0 port 2526 tls-require tag archive

table google_addrs file:/etc/opensmtpd/google_addrs

accept tagged archive from source <google_addrs> for any $relay_archive
accept tagged incoming from source <google_addrs> for domain "ubuntu-helpdesk.example.com" $relay_pickup


# pickup
listen on localhost port 2535 tag pickup

accept tagged pickup from any for any recipient { "archiver@example.com" } $relay_archive
accept tagged pickup from any for domain "ubuntu-helpdesk.example.com" $relay_helpdesk
accept tagged pickup from any for any $relay_gsuite
```


Obviously, there are a few other files for the tables, but I think those are self-explanatory.

I generate the `google_addrs` table with the following script:

```python
#!/usr/bin/env python3
import re
import subprocess
import dns.resolver

netblocks = []

with open("/etc/opensmtpd/google_addrs", "w") as f:
    for record in dns.resolver.query("_spf.google.com", "TXT"): # _spf record
        for block in re.findall("include:(.*?)(?:\s|$)", record.to_text()): # netblocks
            for subrecord in dns.resolver.query(block, "TXT"): # _netblock records
                for subnet in re.findall("ip4:(.*?)(?:\s|$)", subrecord.to_text()): # subnets
                    f.write(subnet + "\n")

subprocess.run(["/usr/sbin/smtpctl", "update", "table", "google_addrs"])
```

For those wishing to use a similar setup, here is my postfix config:

```ini
smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

readme_directory = no

smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = ubuntu-smtp.example.com
alias_maps = 
mydestination = 
relayhost = [localhost]:2535
recipient_delimiter = +
inet_interfaces = loopback-only
inet_protocols = all
always_bcc = archiver@example.com
```

It could almost certainly be made simpler, but this works. The only other thing is to change the default smtp port in `master.cf` to `2530`. (The ports are arbitrary. Pick whatever works for you.)

This setup works, and I've been using it in production about a week. But I'd really like to take postfix out of the mix. With dual/multiple delivery instead of passing everything through postfix, I could just deliver directly to where I needed.

**Comment by edgarpettijohn** [comment] 2017-06-21 00:27
That is fairly complex. I tried to think of a way to make it work without postfix, but was unsuccessful.

**Comment by poolpOrg** [comment] 2017-07-27 13:38
being discussed, we're unsure if we want to achieve this through smtpfd or through the smtp session, also the config rework taking place may affect decisions.

**Comment by korylprince** [comment] 2017-07-30 19:31
Thanks for the update!

**Comment by thctlo** [comment] 2018-02-16 12:41
Hai, im setting up this, and this works fine. 
https://wiki.rtzra.ru/software/postfix/postfix-dualdelivery

**Comment by poolpOrg** [comment] 2019-08-11 14:35
Hello,

Providing multiple actions for a recipient is not doable by design, however now that the filtering API is here, we can easily write a filter that does archiving or dual delivery.

**Comment by korylprince** [comment] 2019-08-13 23:43
Sounds good to me. Is there any documentation on the filtering API beyond your blog posts?

**Comment by poolpOrg** [comment] 2019-08-14 06:14
I'm currently documenting the API 😊

**Comment by poolpOrg** [comment] 2019-08-19 16:02
Filtering API will be part of the next release, including work-in-progress documentation.

Discussed this issue with @ericfaurot, I'll close it because there's nothing that will be done in OpenSMTPD with regard to this, a third-party filter will have to be written.

If someone wants to write on such a filter, I'll be happy to help but this will not land in the OpenSMTPD repository.

**Closed by poolpOrg** 2019-08-19 16:02 UTC
Labels: feature request
