### ISSUE TITLE
PAM configuration

### ISSUE THREAD

**Issue by Yamakaky** [OpenSMTPD/OpenSMTPD#712] opened 2016-08-05 21:02 UTC
Apparently opensmtpd supports PAM, but I can't find any mention of it in the doc. How can I use this feature?

**Comment by poolpOrg** [comment] 2016-08-23 11:55
This is a question for the mailing-list or IRC channel.

Quick reply:

You need to configure --with-auth-pam and provide the auth service name as parameter then configure the PAM side on your system.

I'll close this as it's not a bug, please use proper media and reopen ticket if it turns out you are facing a PAM-related bug.

**Closed by poolpOrg** 2016-08-23 11:55 UTC

**Comment by Yamakaky** [comment] 2016-08-23 13:10
Shouldn't it be on the README?

**Comment by poolpOrg** [comment] 2016-08-23 13:28
why not, feel free to send a pull request and I'll merge
