### ISSUE TITLE
smtpd man page error

### ISSUE THREAD

**Issue by wxcafe** [OpenSMTPD/OpenSMTPD#787] opened 2017-05-26 01:34 UTC
![screenshot from 2017-05-26 03-32-36](https://cloud.githubusercontent.com/assets/3009327/26477188/2897be06-41c4-11e7-8458-6e10ab256c95.png)

I'm pretty sure this is a formatting error

**Comment by poolpOrg** [comment] 2017-07-27 14:40
I will need more details, it renders fine on OpenBSD, Linux and OSX.

What distro are you using ?
Did you build yourself or use a package ?
Can you provide de configure and make / make install log ?

As is, I can't fix as I have virtually no idea where to look :-/

**Comment by wxcafe** [comment] 2017-07-27 15:06
It's fine in the debian package but botched in the ubuntu package, so I'm guessing it has something to do with the ubuntu packaging? If they're just importing the debian package idk what's up but I'm guessing they're changing *something* to it.

**Comment by poolpOrg** [comment] 2017-07-27 17:15
I have no idea, as far as I'm concerned the man page is fine on every OS I check so I'd say the problem is with Ubuntu not with us but I'd like to be sure before the ticket is closed to avoid pulling a Poettering.

**Comment by jdebp** [comment] 2017-08-02 20:51
You'll find the same rendering in on-line versions of that manual [such as this one](https://www.mankier.com/8/smtpd.opensmtpd).  It's unlikely to be the packaging, given that [Ubuntu simply re-uses the Debian source](https://packages.ubuntu.com/source/artful/opensmtpd) with no further patches here, and more likely to be some sort of odd problem with `groff -mandoc`, which tries to auto-detect whether a manual page is using the `man` or `mandoc` macro set, interacting with those particular macros.

**Comment by poolpOrg** [comment] 2017-08-03 07:09
Debian and Ubuntu don't use the same groff ?

I'm going to setup an Ubuntu shortly to understand and fix this issue

**Comment by rghv** [comment] 2017-08-10 06:42
```
ubuntu@ubuntu-xenial:~$ man smtpd|col -bx | tail -10 
SEE ALSO
       smtpd.conf(5), mailwrapper(8), smtpctl(8)

STANDARDS
       Rs %A J. Klensin %D October 2008 %R RFC 5321 %T Simple Mail Transfer Protocol Re

HISTORY
       The smtpd program first appeared in OpenBSD 4.6.

                                                                                $Mdocdate: March 13 2014 $                                                                       SMTPD(8)
ubuntu@ubuntu-xenial:~$ dpkg -l | grep -i smtpd
ii  opensmtpd                        5.7.3p2-1                                  amd64        secure, reliable, lean, and easy-to configure SMTP server
ii  opensmtpd-extras                 5.7.1-1build1                              amd64        addons for the OpenSMTPD SMTP server
ubuntu@ubuntu-xenial:~$ dpkg -L opensmtpd | grep -i man | xargs ls -ld
drwxr-xr-x 32 root root  4096 Jan  4  2017 /usr/share/man
drwxr-xr-x  2 root root 20480 Aug 10 06:38 /usr/share/man/man5
-rw-r--r--  1 root root  1232 Feb 17  2016 /usr/share/man/man5/aliases.5.gz
-rw-r--r--  1 root root   850 Feb 17  2016 /usr/share/man/man5/forward.5.gz
-rw-r--r--  1 root root  8135 Feb 17  2016 /usr/share/man/man5/smtpd.conf.5.gz
-rw-r--r--  1 root root  2357 Feb 17  2016 /usr/share/man/man5/table.5.gz
drwxr-xr-x  2 root root 45056 Aug 10 06:38 /usr/share/man/man8
-rw-r--r--  1 root root  1710 Feb 17  2016 /usr/share/man/man8/makemap.8.gz
-rw-r--r--  1 root root   653 Feb 17  2016 /usr/share/man/man8/newaliases.8.gz
-rw-r--r--  1 root root  1273 Feb 17  2016 /usr/share/man/man8/sendmail.8.gz
-rw-r--r--  1 root root  2700 Feb 17  2016 /usr/share/man/man8/smtpctl.8.gz
-rw-r--r--  1 root root  1204 Feb 17  2016 /usr/share/man/man8/smtpd.8.gz
ubuntu@ubuntu-xenial:~$ uname -a
Linux ubuntu-xenial 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ubuntu-xenial:~$ 
```

confirmed on ubuntu xenial (16.04)

**Comment by ryanakca** [comment] 2017-10-12 22:15
I can't reproduce on Debian, but I'm also running a package several versions more recent than rghv's, so this is not surprising. 
@rghv , can you reproduce this with the most recent version of the manpage? You can fetch the most recent version in Debian and extract it to `tmpdir` by going
`curl -s http://ftp.debian.org/debian/pool/main/o/opensmtpd/opensmtpd_6.0.2p1-2_amd64.deb | dpkg-deb -X - tmpdir`

For reference / comparison's sake, here are the versions available on Debian and Ubuntu:
```
rak@zeta:~$ rmadison -u ubuntu,debian opensmtpd
ubuntu:
 opensmtpd | 5.4.1p1-1       | trusty/universe | source, amd64, arm64, armhf, i386, powerpc, ppc64el
 opensmtpd | 5.4.2p1-4       | vivid/universe  | source, amd64, arm64, armhf, i386, powerpc, ppc64el
 opensmtpd | 5.7.3p2-1       | xenial/universe | source, amd64, arm64, armhf, i386, powerpc, ppc64el, s390x
 opensmtpd | 6.0.2p1-1       | zesty/universe  | source, amd64, arm64, armhf, i386, ppc64el, s390x
 opensmtpd | 6.0.2p1-2build1 | artful/universe | source, amd64, arm64, armhf, i386, ppc64el, s390x
debian:
opensmtpd  | 5.7.3p2-1~bpo8+1 | jessie-backports | source, amd64, arm64, armel, armhf, i386, kfreebsd-amd64, kfreebsd-i386, mips, mipsel, powerpc, ppc64el, s390x
opensmtpd  | 6.0.2p1-2        | stable           | source, amd64, arm64, armel, armhf, i386, mips, mips64el, mipsel, ppc64el, s390x
opensmtpd  | 6.0.2p1-2        | testing          | source
opensmtpd  | 6.0.2p1-2        | unstable         | source
opensmtpd  | 6.0.2p1-2        | unstable-debug   | source
opensmtpd  | 6.0.2p1-2+b1     | testing          | amd64, arm64, armel, armhf, i386, mips, mipsel, ppc64el, s390x
opensmtpd  | 6.0.2p1-2+b1     | unstable         | amd64, arm64, armel, armhf, hurd-i386, i386, kfreebsd-amd64, kfreebsd-i386, mips, mipsel, powerpc, ppc64el, s390x
opensmtpd  | 6.0.2p1-2+b2     | testing          | mips64el
opensmtpd  | 6.0.2p1-2+b2     | unstable         | mips64el
```

**Comment by poolpOrg** [comment] 2018-09-01 10:28
This issue was related to the 5.x version of OpenSMTPD, we don't have the feedback @ryanakca requested and we're heading towards 6.4 release, all man pages have been rewritten since the initial issue was reported.

Closing the issue, feel free to reopen if you still experience the issue with the current portable branch.

**Closed by poolpOrg** 2018-09-01 10:28 UTC
Labels: bug
