### ISSUE TITLE
Lockup when filtering large mails

### ISSUE THREAD

**Issue by awaw** [OpenSMTPD/OpenSMTPD#536] opened 2015-02-03 14:45 UTC
To reproduce: include filter example from extras/filters/filter-stub in your configuration, send mail with several 100 KB from another host (I used `mail me@host </etc/magic`), watch verbose log stop at
`ON DATALINE`. Most of the time it happens at the first try.

**Comment by snimmagadda** [comment] 2015-02-06 14:10
Could you provide the platform on which you are running and also the version of OpenSMTPD. If you haven't tried already, could you reproduce it using the latest master branches of both OpenSMTPD and OpenSMTPD-extras? There was a similar blocking issue that was fixed with this commit 91d82a1a on OpenSMTPD-extras.

**Comment by awaw** [comment] 2015-02-06 15:40
I just confirmed it again on OpenBSD-current amd64 and with the current master branches.

**Comment by poolpOrg** [comment] 2015-02-06 22:47
I'll have a look at this tomorrow evening

**Comment by poolpOrg** [comment] 2015-02-08 11:00
I've taken a look, I think I know what is happening, I'll try to have a fix finished today

**Comment by poolpOrg** [comment] 2015-02-08 11:26
@awaw what is your MUA ?

**Comment by awaw** [comment] 2015-02-08 12:07
* Gilles Chehade <notifications@github.com> [08.02.2015 12:26]:
> @awaw what is your MUA ?

The sending MUA is mail on another OpenBSD host, but this works also
with mutt. It's also independent of content, only size matters.

**Comment by poolpOrg** [comment] 2015-02-08 12:18
For the record:

I thought the issue was related to the bytes accounting between the smtp layer and the filter layer, we already had issues there in the past and they resulted in session locking. I have managed to prove this wrong, the issue is not there.

Here's the issue I've spotted with a bit of context:

The smtp session code reads from the client and passes data to the filter layer. If the client sends faster than the filter can process, we run into a possible DoS as the server will buffer possibly large amounts of data that the filter will never be able to catch up with.

To prevent this from happening, @ericfaurot wrote a congestion detection mechanism which looks at how much data is pending for the filter and temporarily pauses reading from the client and resuming when the pending data is below a threshold. This is transparent for the client, it basically "slows" it down naturally.

The bug you're experiencing is in the code that resumes reading from the client. I'm currently trying to debug this, unfortunately adding logging slows down the daemon enough that the congestion code never kicks in... I'll figure out a way :-p

**Comment by poolpOrg** [comment] 2015-04-20 11:46
Turns out it was way more trickier...
Here's an explanation for future references:

In the ioev layer, in io_dispatch() more specifically, we perform an iobuf_write() which in some situations will trigger EAGAIN or EINTR. In this case the code was jumping to the read event handling which led to a lockup as the processing of the output buffer was aborted.

With the latest code in opensmtpd-extras I no  longer experience lockups.

**Closed by poolpOrg** 2015-04-20 11:46 UTC
