### ISSUE TITLE
Ability to pass destination user to filter

### ISSUE THREAD

**Issue by adufray** [OpenSMTPD/OpenSMTPD#701] opened 2016-06-03 02:32 UTC
Currently filters are able to take advantage of the `on_rcpt` hook to get the destination address, but not the destination account/user, i.e. after expanding from a virtual lookup. This would be nice functionality to have so that it could be passed to filter-spamassassin, then filter-spamassassin could send the User: header to spamd. This would enable user-specific configuration options within SpamAssassin.

**Comment by poolpOrg** [comment] 2016-06-05 12:43
I understand your use-case and its value, however the solution of passing expansion data to filters is not simple as the data is not available in the SMTP layer.

We need to give this some thinking before coming up with a solution.

**Comment by poolpOrg** [comment] 2016-06-30 18:46
This was dicussed with @ericfaurot among other things and the problem is that our filter API currently only covers the PRE-daemon phase of the SMTP dialog.

We're going to have to extend the API further, don't hold your breath it will not happen overnight, but we're meeting at a hackathon in a couple months where we'll design and set up the details for that API extension.

**Comment by poolpOrg** [comment] 2017-07-27 14:23
this will be handled in #773, closing this ticket as the other is assigned and your ticket is now referenced there.

**Closed by poolpOrg** 2017-07-27 14:23 UTC
