### ISSUE TITLE
`@` in virtual context catches all emails

### ISSUE THREAD

**Issue by tlaguz** [OpenSMTPD/OpenSMTPD#1053] opened 2020-04-21 08:35 UTC
OS: OpenBSD 6.6

smtpd.conf:
```
action "local_pdomains" maildir junk alias <aliases>
action "local_vdomains" maildir junk virtual <vusers>
match from any   for domain <vdomains> action "local_vdomains"
match from local for local             action "local_pdomains"
```

vdomains:
```
example.org
example.net
```

vusers:
```
user1@example.com user1
user2@example.net user2
user1@example.net user1
@ usercatchall
```

`user1`, `user2`, `usercatchall` are valid openbsd users.

When line `@ usercatchall` is present, **all** emails (even those for user1@example.com, etc.) are matched for usercatchall.

However:
```
user1@example.com user1
user2@example.net user2
user1@example.com user1
@example.com usercatchall
@example.net usercatchall
```
works as intended.

This is either a bug, or my misunderstandment of the manual. Behavior of catchall is mentioned in: `table(5)`, `makemap(8)`.

**Comment by poolpOrg** [comment] 2020-04-25 09:47
Will investigate this today

**Comment by ericfaurot** [comment] 2020-04-26 13:50
The issue is understood. A fix is coming.

**Comment by poolpOrg** [comment] 2020-04-29 19:09
fix merged

**Closed by poolpOrg** 2020-04-29 19:09 UTC
